<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Customer\Sell\Block\Quote\Success */
?>
<div class="jewllery-image sell-your-jewellery">
    <div class="progress">
        <div id="progress-bar" class="progress-bar" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div>
    </div>

    <div class="success qoute_title">
        <h2><?= $block->escapeHtml(__('Thank you!')) ?></h2>
        <strong><?= $block->escapeHtml(__('Quotation number: '.$block->getQuoteId())) ?></strong>
        <span><?= $block->escapeHtml(__('Thank you for your quotation request.')) ?></span>
        <p><?= $block->escapeHtml(__('We will be in touch soon.')) ?></p>
        <div class="actions-toolbar">
            <div class="secondary">
                <button type="submit" id="quote-btn" class="action submit secondary" title="<?php echo __('Upload another item') ?>">
                    <span><?php echo __('Upload another item') ?></span>
                </button>
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('get-quote-popup')->toHtml(); ?>
            </div>
            <div class="primary">
                <button type="submit" id="find-button" class="action submit primary" title="<?php echo __('Find your perfect diamond') ?>"
                    onclick="window.location.href='<?= $block->getUrl("ringbuilder/diamond") ?>'">
                    <span><?php echo __('Find your perfect diamond') ?></span>
                </button>
            </div>
        </div>
    </div>
</div>