<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()) : ?>
    <!--
    <div class="back-to-signup">
        <span><?= __('New here?') ?></span>
        <a class="signuplink" href="<?php echo $block->getUrl('customer/account/create')?>"><?= __('Create an Account') ?></a>
    </div>
    -->
    <div class="actions-toolbar bottom dont-have-account">
        <div class="pre-primary"><span><?= __("Don't have an account?") ?></span></div>
        <div class="primary">
            <a class="action create" href="<?php echo $block->getUrl('customer/account/create') ?>"><span><?= __('Sign Up') ?></span></a>
        </div>
        <div class="secondary">
            <a class="action remind" href="<?php echo $block->getUrl('customer/account/forgotpassword') ?>"><span><?= __('Reset Password') ?></span></a>
        </div>
    </div>
<?php endif; ?>
<div class="continue-with">
    <?= __('or continue with') ?>
</div>