<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;

    $customblock = $block->getLayout()->createBlock('Magneto\Custom\Block\Addtocart');
    $wishlistItems = $customblock->getWishlistItems();
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()) : ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item) : 
                        $productId = $_item->getId();
                        $productClass = 'product-wishlist-'.$productId;
                        $wishlistClass = '';
                        if (array_key_exists($productId, $wishlistItems)) {
                            $wishlistClass = 'already-in-wishlist';
                            $wishlistParams = $this->helper(\Magento\Wishlist\Helper\Data::class)->getRemoveParams($wishlistItems[$productId]);
                        } else {
                            $wishlistParams = $block->getAddToWishlistParams($_item);
                        }
                    ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <?php if ($showWishlist): ?>
                                <div class="actions-secondary" data-role="add-to-links">
                                    <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                        <a href="#"
                                           data-post='<?= /* @noEscape */ $wishlistParams ?>' class="action towishlist <?php  echo $wishlistClass.' '.$productClass; ?>" data-action="add-to-wishlist " title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                        </a>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php if ($templateType) : ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?= $block->getProductPriceHtml($_item, $type) ?>

                                <?= $block->getProductDetailsHtml($_item) ?>

                                <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                    
                                <?php endif; ?>
                                <?php $class='no-display';
                                if($_item->getData('setting_price')){
                                    $class = '';
                                } ?>
                                <div class="static-text <?php echo $class; ?>">
                                    <span>(<?= $block->escapeHtml(__('Setting Price')) ?>)</span>
                                </div>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        if ($(window).width() < 768) {
            jQuery(document).ready(function () {
                jQuery(".widget-product-grid").not('.slick-initialized').slick({
                    dots: false,
                    arrows: false,
                    infinite: false,
                    speed: 300,
                    slidesToShow: 4,
                    slidesToScroll: 1,
                    responsive: [
                        {
                            breakpoint: 1280,
                            settings: {
                                slidesToShow: 4,
                                slidesToScroll: 4
                            }
                        },
                        {
                            breakpoint: 1024,
                            settings: {
                                slidesToShow: 3,
                                slidesToScroll: 3
                            }
                        },
                        {
                            breakpoint: 768,
                            settings: {
                                slidesToShow: 4,
                                slidesToScroll: 4
                            }
                        },
                        {
                            breakpoint: 767,
                            settings: {
                                slidesToShow: 4,
                                slidesToScroll: 4
                            }
                        },
                        {
                            breakpoint: 640,
                            settings: {
                                slidesToShow: 2,
                                slidesToScroll: 2
                            }
                        },
                        {
                            breakpoint: 480,
                            settings: {
                                slidesToShow: 2.3,
                                slidesToScroll: 1
                            }
                        },
                        {
                            breakpoint: 360,
                            settings: {
                                slidesToShow: 2.3,
                                slidesToScroll: 1
                            }
                        },
                        {
                            breakpoint: 320,
                            settings: {
                                slidesToShow: 2.3,
                                slidesToScroll: 1
                            }
                        },
                        {
                            breakpoint: 315,
                            settings: {
                                slidesToShow: 1.2,
                                slidesToScroll: 1
                            }
                        }
                    ]
                });
            });
        }
    });
</script>