<?php
$item = $block->getSellitem();
$tradeType = $item->getTradetype();
?>
<fieldset class="fieldset tradefieldset hidden">
    <div class="field fieldtrade">
        <label class="head label" for="name">
            <span>
                <?= $block->escapeHtml(__('How to trade in the item ?')) ?>
            </span>
        </label>
        <div class="control">
            <div class="sub-control">
                <input type="radio" checked="true" class="radio" id="online" data-validate="{'validate-one-required-by-name':true}" name="trade_type" value="1">
                <label class="label" for="online">
                    <?= $block->escapeHtml(__('Online')) ?>
                </label>
            </div>
            <div class="sub-control">
                <input type="radio" class="radio" id="inperson" data-validate="{'validate-one-required-by-name':true}" name="trade_type" value="2">
                <label class="label" for="inperson">
                    <?= $block->escapeHtml(__('In Person')) ?>
                </label>
            </div>
        </div>
    </div>
    <div class="actions-toolbar hidden">
        <div class="primary">
            <button id="trade_type_selection" type="button" title="<?= $block->escapeHtml(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</fieldset>