<?php
/**
 *
 * @category: Magepow
 * @Copyright (c) 2014 Magepow  (<https://www.magepow.com>)
 * @authors: Magepow (<magepow<support@magepow.com>>)
 * @date:    2021-04-27 16:26:18
 * @license: <http://www.magepow.com/license-agreement>
 * @github: <https://github.com/magepow>
 */
 /** @var \Magepow\AjaxWishlist\Block\Form\Login $block */
?>
<?php
    $helper = $this->helper('Magepow\AjaxWishlist\Helper\Data');
    $imgWishlist = $helper->getConfigModule('general/image');
    $urlMedia = $helper->getBaseUrlMedia();
?>
<?php if (!$block->customerIsAlreadyLoggedIn()): ?>

    <div id="customer-popup-login" class="customer-popup-login _disabled">
        <div class="block block-customer-login">
            <div class="social-login-title">
                <h2 class="login-title"><?= __('Sign In') ?></h2> 
            </div>
            <div class="block social-login-customer-authentication col-mp mp-7" id="social-login-authentication"> 
                <div class="block-title"> 
                    <span id="block-customer-login-heading" role="heading" aria-level="2"><?= __('Registered Customers') ?></span>
                </div> 
                <div class="block-content" aria-labelledby="block-customer-popup-login-heading">
                    <form class="form form-login"
                          action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
                          method="post"
                          id="customer-popup-login-form"
                          data-mage-init='{"validation":{}}'>
                        <?php echo $block->getBlockHtml('formkey'); ?>
                        <input type="hidden" name="redirect_url" value="<?php echo $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>" />
                        <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                            <div class="messages"></div>
                            <div class="field email required">
                                <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                                <div class="control">
                                    <input name="username" value="" <?php if ($block->isAutocompleteDisabled()):?> autocomplete="off"<?php endif; ?> id="email-login" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                                </div>
                            </div>
                            <div class="field password required">
                                <label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                                <div class="control">
                                    <input name="password" type="password" <?php if ($block->isAutocompleteDisabled()):?> autocomplete="off"<?php endif; ?> class="input-text" id="pass-login" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true}" >
                                </div>
                            </div>
                            <div class="actions-toolbar">
                                <div class="primary"><button type="submit" class="action login primary" name="send" id="send2-login"><span><?php /* @escapeNotVerified */ echo __('Login') ?></span></button></div>
                                <div class="secondary"><a href="<?php echo $this->getUrl('customer/account/forgotpassword/') ?>"><?= __("Forgot Your Password")?>?</a>
                                </div>
                               
                                <?php if ($block->getRegistration()->isAllowed()): ?>
                                    
                                    <div class="secondary m-0"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getCustomerRegistrationUrl() ?>" id="customer-popup-registration"><span><?php /* @escapeNotVerified */ echo __('Create an Account?') ?></span></a></div>
                                <?php endif; ?>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
            <div class="block social-login-authentication-channel col-mp mp-5"> 
                <div class="block-title"><?= __('Or Sign In With') ?></div>               
                <?php echo $block->getLayout()
                            ->createBlock("Mageplaza\SocialLogin\Block\Popup\Social")
                            ->setTemplate("Mageplaza_SocialLogin::form/social.phtml")
                            ->toHtml();
                ?>    
            </div>
        </div>
        <script type="text/x-magento-init">
            {
                "#customer-popup-login": {
                    "Magepow_AjaxWishlist/js/action/customer-authentication-popup": {
                        "innerWidth": "400"
                    }
                }
            }
        </script>
    </div>
<?php endif; ?>
