<?php
/**
 * @author Gemfind Team
 */
?>
<?php
$settings = $block->getStyleSettings();

if ($settings && sizeof($settings) > 0) {
    $selectedItemTextColor = '#000000';
    $buttonTextHoverColor = $buttonTextColor = '#ffffff';
    $sliderColor = $settings['settings']['linkColor'][0]->color2;
    $selectedItemColor = $settings['settings']['linkColor'][0]->color2;
    $selectedItemhoverColor = $settings['settings']['hoverEffect'][0]->color2;
    $gridColor = $settings['settings']['columnHeaderAccent'][0]->color2;
    $gridHoverColor = $settings['settings']['hoverEffect'][0]->color2;
    $buttonBackgroundColor = $settings['settings']['callToActionButton'][0]->color2;
    $buttonhoverColor = $settings['settings']['hoverEffect'][0]->color2;
    $linkColor = $settings['settings']['linkColor'][0]->color2;
    $linkHoverColor = $settings['settings']['hoverEffect'][0]->color2;
    $additionalCSS = $block->getAdditionalCss();
    ?>

<style>
    #search-diamonds .noUi-connect { background-color: <?=$sliderColor ?>; border-color: <?=$sliderColor ?>; }
    #search-diamonds .slider_wrapper .noUi-handle {background: <?=$sliderColor ?>; border-color: <?=$sliderColor ?>;}    
.flow-tabs .tab-section li.tab-li.active a, .diamond-filter-title{background: <?=$gridColor ?>;}
    .flow-tabs .tab-section li.tab-li.active a:after{border-color: transparent transparent transparent <?=$gridColor ?>;}
    .ui-slider-horizontal .ui-slider-range { background-color: <?=$sliderColor ?>; border-color: <?=$sliderColor ?>; }
    .ui-slider .ui-slider-tooltip, .ui-widget-content .ui-slider-handle { background-color: <?=$sliderColor ?>; }
    .ui-slider .ui-slider-tooltip .ui-tooltip-pointer-down-inner {border-top: 7px solid <?=$sliderColor ?> !important;}
    .diamond-filter-title ul li.active a, .diamond-filter-title ul li a:hover {color: <?=$linkHoverColor ?>; text-shadow: 0px 0px 1px <?=$linkHoverColor ?>;}
    .product-controler ul li a { color: <?=$linkColor ?>;}
    .product-controler ul li a:hover {color: <?=$linkHoverColor ?>;}
    .filter-for-shape ul li .shape-type.selected {background: <?=$selectedItemColor ?>;}
    .filter-for-shape ul li .shape-type:hover{background: <?=$selectedItemhoverColor ?>;}
    .filter-for-shape .cut-main ul li.active {background: <?=$selectedItemColor ?>; color: <?=$selectedItemTextColor ?>;}
    .filter-advanced .accordion:before, .change-view-result ul li.list-view a.active:before, .change-view-result ul li.grid-view a.active:before, .change-view-result ul li a.active:before, .search-in-table button{background-color: <?=$buttonBackgroundColor ?>; color: <?=$buttonTextColor ?>;}
    .diamond-filter-title ul li a{color: #ffffff; }
    .diamond-filter-title .kendana svg#Capa_1{fill: #ffffff; color: #ffffff; }
    .diamond-filter-title .kendana svg#Capa_1{fill: #ffffff; color: #ffffff; }
    .diamond-filter-title ul li.active .kendana svg#Capa_1{fill: <?=$linkColor ?>; color: #ffffff; }
    .diamond-filter-title ul li.active .kendana svg#Capa_1:hover{fill: <?=$linkHoverColor ?>;  color: #ffffff;}
    .search-details .table thead tr th {background: <?=$gridColor ?>; color: <?=$buttonTextColor ?>; }
    .search-details .table tbody tr th.table-selecter .state label:before {border: 2px solid <?=$selectedItemColor ?>; }
    .search-details .table tbody tr th.table-selecter input[type="checkbox"]:checked~.state label:after {background-color: <?=$selectedItemColor ?>; }
    .search-details .table tbody tr th.table-selecter .state label:after {border: 1px solid <?=$selectedItemColor ?>; }
    .search-details .table tbody tr th.table-selecter input[type="checkbox"]:checked~.state label:before {background-color: <?=$selectedItemColor ?>;}
    .search-details .table tbody tr:hover td, .search-details .table tbody tr:hover th{background: <?=$gridHoverColor ?>; color: <?=$buttonTextColor ?>; }    
    .search-details .table tbody tr:hover td a{ color: <?=$buttonTextColor ?>; }    
    .grid-paginatin ul li.active {background: <?=$buttonBackgroundColor ?>; color: <?=$buttonTextColor ?>;}
    .grid-paginatin ul li.active a{background: <?=$buttonBackgroundColor ?>; color: <?=$buttonTextColor ?>;}
    .grid-paginatin ul li.active:hover, .diamond-page .diamond-action button.addtocart:hover, .prefrence-action .preference-btn:hover, .compare-actions .view-product:hover, .grid-paginatin a#compare-main:hover, .grid-paginatin ul li:not(.grid-previous):not(.grid-next) a:hover, .compare-actions .delete-row:before, .compare-actions .delete-row{background: <?=$buttonhoverColor ?>; color: <?=$buttonTextHoverColor ?>; }
    .change-view-result ul li.list-view a:hover, .change-view-result ul li.grid-view a:hover, .change-view-result ul li a:hover{color: <?=$buttonTextHoverColor ?>; }
    .search-in-table button:hover { background-color: <?=$buttonhoverColor ?>; color: <?=$buttonTextHoverColor ?>; }
    .search-product-grid .product-details .product-box-pricing span {color: <?=$selectedItemColor ?>; }
    .product-details .product-box-action label {color: <?=$selectedItemColor ?>; }
    .product-details .product-box-action .state label:before { border: 2px solid <?=$selectedItemColor ?>; }
    .product-details .product-box-action .state label:after {border: 1px solid <?=$selectedItemColor ?>;}
    .product-details .product-box-action input[type="checkbox"]:checked~.state label:before {background: <?=$selectedItemColor ?>;}
    .product-details .product-box-action input[type="checkbox"]:checked~.state label:after {background-color: <?=$selectedItemColor ?>;}
    .product-controler ul li:before {background-color: <?=$selectedItemColor ?>;}
    .specification-title h4 a {color: <?=$linkColor ?>;}
    .diamond-request-form .form-field .diamond-action span {color: <?=$selectedItemColor ?>;}
    .ring-request-form .form-field .diamond-action span {color: <?=$selectedItemColor ?>;}
    .diamond-page .diamond-action button.addtocart {background: <?=$buttonBackgroundColor ?>; color: <?=$buttonTextColor ?>; }
    .diamond-action button.addtocart {background-color: <?=$buttonBackgroundColor ?> !important;background: <?=$buttonBackgroundColor ?>; color: <?=$buttonTextColor ?>; }
    .diamond-info h2 span {color: <?=$linkColor ?>; }
    .diamond-request-form .form-field label input:focus, .diamond-request-form .form-field label textarea:focus {border-color: <?=$selectedItemColor ?>;}
    .prefrence-action .preference-btn {background: <?=$buttonBackgroundColor ?>; color: <?=$buttonTextColor ?>; }
    .diamond-request-form .form-field .prefrence-area input:checked~label:before {background: <?=$selectedItemColor ?>;}
    .ring-request-form .form-field .prefrence-area input:checked~label:before {background: <?=$selectedItemColor ?>;}
    .compare-product .filter-title ul.filter-left li.active a {color: <?=$linkHoverColor ?>; }
    .color-filter ul li.active, .filter-details .polish-depth ul li.active { background: <?=$selectedItemColor ?>; color: <?=$buttonTextColor ?>;}
    .color-filter ul li:hover, .filter-details .polish-depth ul li:hover, .filter-for-shape .cut-main ul li:hover {background: <?=$selectedItemhoverColor ?>; color: <?=$selectedItemTextColor ?>; }
    .ui-datepicker .ui-datepicker-prev span, .ui-datepicker .ui-datepicker-next span {border-color: transparent <?=$selectedItemColor ?> transparent transparent; }  
    .ui-datepicker .ui-datepicker-next span {border-color: transparent transparent transparent <?=$selectedItemColor ?>; }    
    .ui-datepicker .ui-datepicker-calendar .ui-datepicker-today {background: <?=$selectedItemColor ?>; }
    .grid-paginatin a#compare-main {background: <?=$buttonBackgroundColor ?>; color: <?=$buttonTextColor ?>;}
    .product-controler ul li a:hover {color: <?=$linkHoverColor ?>;}
    .product-slide-button .trigger-info:before{color:<?=$buttonBackgroundColor ?> !important; }
    .compare-actions .view-product {background: <?=$buttonBackgroundColor ?>; color: <?=$buttonTextColor ?>;}
    .compare-info table tbody tr th:nth-child(1) a:hover:before, .compare-info table tbody tr th:nth-child(1) a:before{background: <?=$buttonBackgroundColor ?>;}
    .compare-product .filter-title ul.filter-left li a{color:<?=$linkColor ?>;}
    .compare-product .filter-title ul.filter-left li a:hover{color:<?=$linkHoverColor ?>;}
    .sumo_pagesize .optWrapper ul.options li.opt.selected{background-color: <?=$linkColor ?>; color: #000;}
    .sumo_pagesize .optWrapper ul.options li.opt:hover{background-color: <?=$linkHoverColor ?>; color: #000;}
    .SumoSelect > .optWrapper > .options li.opt.selected{background-color: <?=$linkColor ?>; color: #000;}
    .SumoSelect > .optWrapper > .options li.opt:hover{background-color: <?=$linkHoverColor ?>; color: #000;}
    .SumoSelect > .optWrapper.multiple > .options li.opt.selected span i, .SumoSelect .select-all.selected > span i{background-color: <?=$buttonBackgroundColor.' !important' ?>;}
    .diamond-report .view_text a{color:<?=$buttonBackgroundColor ?> !important;}
    .internalusemodel.modal-slide .modal-inner-wrap, .dealerinfopopup.modal-slide .modal-inner-wrap{border:2px solid <?=$selectedItemColor ?>;}
    .internalusemodel.modal-slide header button, .dealerinfopopup.modal-slide header button, #internaluseform button.preference-btn{background:<?=$buttonBackgroundColor.' !important' ?>;  box-shadow: none; color: <?=$buttonTextColor ?>; }
    a.internaluselink {color: <?=$buttonBackgroundColor ?>;}
    a.internaluselink:hover {color: <?=$linkHoverColor ?>;}
    .internalusemodel .msg{padding: 2px; margin-bottom: 2px;}
    .internalusemodel .msg .error{color: #e40f0f;}
    .internalusemodel .msg .success{color: #29a529;}
    .breadcrumbs ul li a{color: <?=$linkColor ?> !important;}
    .breadcrumbs ul li a:hover{color: <?=$linkHoverColor ?> !important;}
    svg#Capa_1{fill: <?=$linkColor ?>;}
    svg#Capa_1:hover{fill: <?=$linkHoverColor ?>;}
    .kendana svg#Capa_1{fill: <?=$linkColor ?>; height: 16px; width: 16px;}
    .kendana svg#Capa_1:hover{fill: <?=$linkHoverColor ?>;}
    .noUi-marker-large {
    background: #fff;
}
tr.selected_row th, tr.selected_row td {
    background:  <?=$linkColor ?>!important;
    color:#fff;
}
tr.selected_row:hover th, tr.selected_row:hover td {
    background:  <?=$linkHoverColor ?>!important;
    color:#fff;
}
.noUi-pips-horizontal{padding:0px; height:0px;}
.search-details .table tbody tr.selected_row th.table-selecter .state label:before {
    border: 2px solid #ffffff;
}
.search-details .table tbody tr.selected_row th.table-selecter .state label:after {
    border: 1px solid #ffffff;
}
    <?=$additionalCSS ?>
</style>
<?php } ?>
