<?php $gemfindStatus = $block->isGemfindEnable();
$para = $block->getPara(); 

$originval = $defaultview = '';
$defaultview = $block->getDefaultView();
if ($block->getSaveFilterCookieData()) {
    $savedfilter = json_decode($block->getSaveFilterCookieData());
} elseif($block->getSaveBackValueCookieData()) {
      $savedfilter = json_decode($block->getSaveBackValueCookieData());
} else {
  $savedfilter = '';
}

$settingcoockieval = array(); $labsettings = false;
if($block->getRingCookieData()){
   $settingcoockieval = $block->getRingCookieData();   
   if($settingcoockieval->Filtermode == 'labsettings'){
      $labsettings = true;
   } else {
      $labsettings = false;
   }
} else {
   $labsettings = false;
}

if ($gemfindStatus && sizeof($block->getActiveNavigation()) > 0) : ?>



<div id="search-diamonds" class="flow-tabs">

<div class="tab-section">
<ul class="tab-ul">
         <?php if($block->checkRingCookie()) { ?>
         <?php if($labsettings){ ?>
         <li class="tab-li"><div><a href="<?php echo $block->getUrl('ringbuilder/settings').'type/labsettings'; ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Setting'); ?></strong></span><i class="ring-icon tab-icon"></i></a></div></li>
		  <?php } else { ?>
			 <li class="tab-li"><div><a href="<?php echo $block->getUrl('ringbuilder/settings'); ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Setting'); ?></strong></span><i class="ring-icon tab-icon"></i></a></div></li>
		  <?php } ?>
         <?php } else { ?>
         <li class="tab-li active"><div><a href="<?php echo $block->getUrl('ringbuilder/diamond'); ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Diamond'); ?></strong></span><i class="diamond-icon tab-icon"></i></a></div></li>         
         <?php } ?>
         <?php if(!$block->checkRingCookie()) { ?>
         <?php if($labsettings){ ?>
         <li class="tab-li"><div><a href="<?php echo $block->getUrl('ringbuilder/settings').'type/labsettings'; ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Setting'); ?></strong></span><i class="ring-icon tab-icon"></i></a></div></li>
		  <?php } else { ?>
			 <li class="tab-li"><div><a href="<?php echo $block->getUrl('ringbuilder/settings'); ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Setting'); ?></strong></span><i class="ring-icon tab-icon"></i></a></div></li>
		  <?php } ?>
         <?php } else { ?>
         <li class="tab-li active"><div><a href="<?php echo $block->getUrl('ringbuilder/diamond'); ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Diamond'); ?></strong></span><i class="diamond-icon tab-icon"></i></a></div></li>
         <?php } ?>
         <li class="tab-li"><div><a href="javascript:;"><span class="tab-title"><?php echo __('Review'); ?><strong><?php echo __('Complete Ring'); ?></strong></span><i class="finalring-icon tab-icon"></i></a></div></li>
</ul> 
</div>
<div class="to-hide">
  <div class="loading-mask gemfind-loading-mask" style="display: none">
    <div class="loader gemfind-loader"><p>Please wait...</p></div> 
  </div>

<form id="search-diamonds-form" method="post" action="<?= $block->escapeUrl($block->getFormAction()) ?>" 

   class="search_form">

   <input name="submitby" id="submitby" type="hidden" value="">

   <input name="defaultshapevalue" id="defaultshapevalue" type="hidden" value="<?php echo $block->getShapedefaultfilter(); ?>">
   
   <input name="baseurl" id="baseurl" type="hidden" value="<?php echo $this->getBaseUrl(); ?>">

   <section class="diamonds-search">

      <div class="d-container">

         <div class="d-row">

            <div class="diamonds-details no-padding">

               <div class="diamonds-filter">

                  <div class="diamond-filter-title">

                     <ul class="filter-left" id="navbar">

                        <?php $i = 0; foreach ($block->getActiveNavigation() as $key => $value) { 

                        if($value){ 

                           if($value != 'Compare'){

                        $id = strtolower($key); ?>

                        <?php if(isset($para)){ ?>

                           <li <?php if($id == $para){ ?> class="active" <?php } ?> id="<?php echo $id; ?>">

                           <a href="javascript:;" onclick="mode(<?php echo $id ?>); diamondsearhmain();" title="<?php echo $value;?>">

                              <?php echo $value; ?>

                           </a>
							<span class="show-filter-info-nav kendana" ><svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 23.625 23.625" style="enable-background:new 0 0 23.625 23.625;" xml:space="preserve">
<g>
  <path style="" d="M11.812,0C5.289,0,0,5.289,0,11.812s5.289,11.813,11.812,11.813s11.813-5.29,11.813-11.813
    S18.335,0,11.812,0z M14.271,18.307c-0.608,0.24-1.092,0.422-1.455,0.548c-0.362,0.126-0.783,0.189-1.262,0.189
    c-0.736,0-1.309-0.18-1.717-0.539s-0.611-0.814-0.611-1.367c0-0.215,0.015-0.435,0.045-0.659c0.031-0.224,0.08-0.476,0.147-0.759
    l0.761-2.688c0.067-0.258,0.125-0.503,0.171-0.731c0.046-0.23,0.068-0.441,0.068-0.633c0-0.342-0.071-0.582-0.212-0.717
    c-0.143-0.135-0.412-0.201-0.813-0.201c-0.196,0-0.398,0.029-0.605,0.09c-0.205,0.063-0.383,0.12-0.529,0.176l0.201-0.828
    c0.498-0.203,0.975-0.377,1.43-0.521c0.455-0.146,0.885-0.218,1.29-0.218c0.731,0,1.295,0.178,1.692,0.53
    c0.395,0.353,0.594,0.812,0.594,1.376c0,0.117-0.014,0.323-0.041,0.617c-0.027,0.295-0.078,0.564-0.152,0.811l-0.757,2.68
    c-0.062,0.215-0.117,0.461-0.167,0.736c-0.049,0.275-0.073,0.485-0.073,0.626c0,0.356,0.079,0.599,0.239,0.728
    c0.158,0.129,0.435,0.194,0.827,0.194c0.185,0,0.392-0.033,0.626-0.097c0.232-0.064,0.4-0.121,0.506-0.17L14.271,18.307z
     M14.137,7.429c-0.353,0.328-0.778,0.492-1.275,0.492c-0.496,0-0.924-0.164-1.28-0.492c-0.354-0.328-0.533-0.727-0.533-1.193
    c0-0.465,0.18-0.865,0.533-1.196c0.356-0.332,0.784-0.497,1.28-0.497c0.497,0,0.923,0.165,1.275,0.497
    c0.353,0.331,0.53,0.731,0.53,1.196C14.667,6.703,14.49,7.101,14.137,7.429z"/>
</g>
</svg></span>
                        </li>

                        <?php } else { ?>

                           <li <?php if($i == 0){ ?> class="active" <?php } ?> id="<?php echo $id; ?>">

                           <a href="javascript:;" onclick="mode(<?php echo $id ?>); diamondsearhmain();" title="<?php echo $value;?>">

                              <?php echo $value; ?>

                           </a>
							<span class="show-filter-info-nav kendana" ><svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 23.625 23.625" style="enable-background:new 0 0 23.625 23.625;" xml:space="preserve">
<g>
  <path style="" d="M11.812,0C5.289,0,0,5.289,0,11.812s5.289,11.813,11.812,11.813s11.813-5.29,11.813-11.813
    S18.335,0,11.812,0z M14.271,18.307c-0.608,0.24-1.092,0.422-1.455,0.548c-0.362,0.126-0.783,0.189-1.262,0.189
    c-0.736,0-1.309-0.18-1.717-0.539s-0.611-0.814-0.611-1.367c0-0.215,0.015-0.435,0.045-0.659c0.031-0.224,0.08-0.476,0.147-0.759
    l0.761-2.688c0.067-0.258,0.125-0.503,0.171-0.731c0.046-0.23,0.068-0.441,0.068-0.633c0-0.342-0.071-0.582-0.212-0.717
    c-0.143-0.135-0.412-0.201-0.813-0.201c-0.196,0-0.398,0.029-0.605,0.09c-0.205,0.063-0.383,0.12-0.529,0.176l0.201-0.828
    c0.498-0.203,0.975-0.377,1.43-0.521c0.455-0.146,0.885-0.218,1.29-0.218c0.731,0,1.295,0.178,1.692,0.53
    c0.395,0.353,0.594,0.812,0.594,1.376c0,0.117-0.014,0.323-0.041,0.617c-0.027,0.295-0.078,0.564-0.152,0.811l-0.757,2.68
    c-0.062,0.215-0.117,0.461-0.167,0.736c-0.049,0.275-0.073,0.485-0.073,0.626c0,0.356,0.079,0.599,0.239,0.728
    c0.158,0.129,0.435,0.194,0.827,0.194c0.185,0,0.392-0.033,0.626-0.097c0.232-0.064,0.4-0.121,0.506-0.17L14.271,18.307z
     M14.137,7.429c-0.353,0.328-0.778,0.492-1.275,0.492c-0.496,0-0.924-0.164-1.28-0.492c-0.354-0.328-0.533-0.727-0.533-1.193
    c0-0.465,0.18-0.865,0.533-1.196c0.356-0.332,0.784-0.497,1.28-0.497c0.497,0,0.923,0.165,1.275,0.497
    c0.353,0.331,0.53,0.731,0.53,1.196C14.667,6.703,14.49,7.101,14.137,7.429z"/>
</g>
</svg></span>
                        </li>   

                        <?php } ?>

                     <?php $i++; } else { ?>

                        <li><a href="javascript:;" id="comparetop" title="<?php echo __('Compare');?>"><?php echo __('Compare');?></a></li>

                     <?php } } } ?>

                     </ul>

                     <ul class="filter-right">

                        <li><a href="javascript:;" onclick="SaveFilter();"><?php echo __('Save Search');?></a></li>

                        <li><a href="javascript:;" onclick="ResetFilter();"><?php echo __('Reset');?></a></li>

                     </ul>

                  </div>

                  <div class="filter-main-div" id="filter-main-div">
                    <div class="placeholder-content">
                      <div class="placeholder-content_item box1"></div>
                      <div class="placeholder-filter">
                        <div class="placeholder-filter_inner placeholder-flex">
                          <div class="placeholder-content_item head"></div>
                          <div class="placeholder-filter_box placeholder-flex">
                            <div class="placeholder-content_item box"></div>
                            <div class="placeholder-content_item box"></div>
                            <div class="placeholder-content_item box"></div>
                            <div class="placeholder-content_item box"></div>
                            <div class="placeholder-content_item box"></div>
                            <div class="placeholder-content_item box"></div>
                            <div class="placeholder-content_item box"></div>
                            <div class="placeholder-content_item box"></div>
                            <div class="placeholder-content_item box"></div>
                            <div class="placeholder-content_item box"></div>                  
                          </div>
                        </div>
                        <div class="placeholder-filter_inner placeholder-flex">
                          <div class="placeholder-content_item head"></div>
                          <div class="placeholder-content_item box-list placeholder-filter_box"></div>
                        </div>
                        <div class="placeholder-filter_inner placeholder-flex">
                          <div class="placeholder-content_item head"></div>
                          <div class="placeholder-content_item box-list placeholder-filter_box"></div>
                        </div>
                        <div class="placeholder-filter_inner placeholder-flex">
                          <div class="placeholder-content_item head"></div>
                          <div class="placeholder-content_item box-list placeholder-filter_box"></div>
                        </div>
                        <div class="placeholder-filter_inner placeholder-flex">
                          <div class="placeholder-content_item head"></div>
                          <div class="placeholder-content_item box-list placeholder-filter_box"></div>
                        </div>
                      <div class="placeholder-content_item"></div>
                      </div>
                    </div>

                  </div>

               </div>

            </div>

         </div>

      </div>

   </section>

   <?php $i = 0; foreach ($block->getActiveNavigation() as $key => $value) { 

      $id = strtolower($key);

      if(isset($para)){

         if($id == $para){ ?>

            <input type="hidden" name="filtermode" id="filtermode" value="<?php echo $id; ?>" />

        <?php }

      } else {

          if($i == 0) { ?>

            <input type="hidden" name="filtermode" id="filtermode" value="<?php echo $id; ?>" />

          <?php }

      } $i++; } ?>

   <input type="submit" name="Submit" id="submit" style="visibility: hidden;">

</form>

</div>
</div>
<div class="result filter-advanced">
  <div class="placeholder-content">

    <?php
     if(isset($savedfilter->viewmode)){
          $resultviewmode = $savedfilter->viewmode;
          } else { 
          $resultviewmode = $defaultview; 
          } 
    ?>
    <?php if($resultviewmode == 'grid') { ?>
      <!-- DL Grid HTML -->
    <div class="placeholder-content_table">
      <div class="placeholder-product_list">
        <div class="placeholder-content_list">
          <div class="placeholder-content_item round-img"></div>
          <div class="placeholder-content_item placeholder-product"></div>
          <div class="placeholder-content_item placeholder-price"></div>
          <div class="placeholder-content_item placeholder-compare"></div>
        </div>
        <div class="placeholder-content_list">
          <div class="placeholder-content_item round-img"></div>
          <div class="placeholder-content_item placeholder-product"></div>
          <div class="placeholder-content_item placeholder-price"></div>
          <div class="placeholder-content_item placeholder-compare"></div>
        </div>
        <div class="placeholder-content_list">
          <div class="placeholder-content_item round-img"></div>
          <div class="placeholder-content_item placeholder-product"></div>
          <div class="placeholder-content_item placeholder-price"></div>
          <div class="placeholder-content_item placeholder-compare"></div>
        </div>
        <div class="placeholder-content_list">
          <div class="placeholder-content_item round-img"></div>
          <div class="placeholder-content_item placeholder-product"></div>
          <div class="placeholder-content_item placeholder-price"></div>
          <div class="placeholder-content_item placeholder-compare"></div>
        </div>
        <div class="placeholder-content_list">
          <div class="placeholder-content_item round-img"></div>
          <div class="placeholder-content_item placeholder-product"></div>
          <div class="placeholder-content_item placeholder-price"></div>
          <div class="placeholder-content_item placeholder-compare"></div>
        </div>
        <div class="placeholder-content_list">
          <div class="placeholder-content_item round-img"></div>
          <div class="placeholder-content_item placeholder-product"></div>
          <div class="placeholder-content_item placeholder-price"></div>
          <div class="placeholder-content_item placeholder-compare"></div>
        </div>
        <div class="placeholder-content_list">
          <div class="placeholder-content_item round-img"></div>
          <div class="placeholder-content_item placeholder-product"></div>
          <div class="placeholder-content_item placeholder-price"></div>
          <div class="placeholder-content_item placeholder-compare"></div>
        </div>
        <div class="placeholder-content_list">
          <div class="placeholder-content_item round-img"></div>
          <div class="placeholder-content_item placeholder-product"></div>
          <div class="placeholder-content_item placeholder-price"></div>
          <div class="placeholder-content_item placeholder-compare"></div>
        </div>
        <div class="placeholder-content_list">
          <div class="placeholder-content_item round-img"></div>
          <div class="placeholder-content_item placeholder-product"></div>
          <div class="placeholder-content_item placeholder-price"></div>
          <div class="placeholder-content_item placeholder-compare"></div>
        </div>
        <div class="placeholder-content_list">
          <div class="placeholder-content_item round-img"></div>
          <div class="placeholder-content_item placeholder-product"></div>
          <div class="placeholder-content_item placeholder-price"></div>
          <div class="placeholder-content_item placeholder-compare"></div>
        </div>
        <div class="placeholder-content_list">
          <div class="placeholder-content_item round-img"></div>
          <div class="placeholder-content_item placeholder-product"></div>
          <div class="placeholder-content_item placeholder-price"></div>
          <div class="placeholder-content_item placeholder-compare"></div>
        </div>
        <div class="placeholder-content_list">
          <div class="placeholder-content_item round-img"></div>
          <div class="placeholder-content_item placeholder-product"></div>
          <div class="placeholder-content_item placeholder-price"></div>
          <div class="placeholder-content_item placeholder-compare"></div>
        </div>  
      </div>
    </div>
  <!-- DL Grid HTML -->
    <?php } ?>
    <?php if($resultviewmode == 'list') { ?>
  <!-- DL list HTML -->
    <div class="placeholder-content_table">
        <div class="placeholder-content_tableInner">
            <div class="placeholder-content_item box1"></div>
            <div class="placeholder-content_item placeholder-table_listing"> </div>
            <div class="placeholder-content_item placeholder-table_listing"> </div>
            <div class="placeholder-content_item placeholder-table_listing"> </div>
            <div class="placeholder-content_item placeholder-table_listing"> </div>
            <div class="placeholder-content_item placeholder-table_listing"> </div>
            <div class="placeholder-content_item placeholder-table_listing"> </div>
        </div>
    </div>
  <!-- End here DL list HTML -->  
    <?php } ?>
    <div class="placeholder-content_footer placeholder-flex">
      <div class="placeholder-content_item button-box"></div>
      <div class="placeholder-content_item head"></div>
    </div>
  </div>
</div>
<div id="popup-modal"><p></p></div>
<?php else: echo __('Gemfind Diamond Search Extension not enabled.'); endif; ?>
<input type="hidden" name="gemfind_rbdl_version" value="2.6" />
<style>
  .placeholder-content {
    max-width: 100%;
    margin: 0 auto;
  }
    .placeholder-content .placeholder-content_item.box1 {
    height: 50px;
    margin-bottom: 10px;
}
.placeholder-content .placeholder-filter_inner  {
    margin-bottom: 12px;
}
.placeholder-content .placeholder-flex {
    display: flex;
    flex-wrap: wrap;
}

.placeholder-content .head {
    max-width: 160px;
    width: 100%;
    margin-right: 20px;
    align-self: center;
}

.placeholder-content .placeholder-filter_box {
    width: calc(100% - 180px);
}

.placeholder-content .placeholder-filter .box {
    width: 9%;
    height: 60px;
    margin-right: 1.1%;
}

.placeholder-content .box:last-child {
    margin-right: 0;
}
.placeholder-content .placeholder-filter .box-list {
    height: 50px;
}
.placeholder-content .placeholder-content_table {
    display: inline-block;
    width: 100%;
}
.placeholder-content .placeholder-product_list .placeholder-content_list:nth-child(4n + 0) {
  margin-right: 0;
}
.placeholder-content .placeholder-product_list .placeholder-content_list {
    margin-bottom: 15px;
    width: 23.4%;
    float: left;
    margin-right: 2%;
    margin-bottom: 2.2%;
    border: 1px solid #eee;
    padding: 10px;
    box-sizing: border-box;
}
.placeholder-content .placeholder-content_item.round-img {
    width: 150px;
    height: 150px;
    border-radius: 50%;
    margin: 0 auto 12px;
}
.placeholder-content .placeholder-content_list .placeholder-content_item {
  max-width: 80%;
  margin: 0 auto 10px;
}
.placeholder-content .placeholder-filter {
    margin-bottom: 60px;
    padding: 15px;
    background: #fafafa;
    border: 1px solid #eee ;
}

.placeholder-content .placeholder-content_footer .button-box {
    height: 50px;
    max-width: 150px;
    width: 100%;
    margin-top: 20px;
}
.placeholder-content .placeholder-content_footer {
    align-items: center;
    justify-content: space-between;
}
.placeholder-content .placeholder-content_footer .head {
    margin: 0;
}
.placeholder-content .placeholder-content_item {
  overflow: hidden;
   background: #000;
   position: relative;
   animation-duration: 0.8s;
   animation-fill-mode: forwards;
   animation-iteration-count: infinite;
   animation-timing-function: linear;
   animation-name: placeholderAnimate;
   background: #f6f7f8;
   background: linear-gradient(to right, #eee 2%, #ddd 18%, #eee 33%);
   background-size: 1300px;
  height: 20px;
  margin-bottom: 20px;
}
@keyframes placeholderAnimate {
  0% {
     background-position: -650px 0;
  }
   100% {
     background-position: 650px 0;
  }
}
@media (max-width:  992px) {
  .placeholder-content .placeholder-filter_box {
      width: 100%;
  }
  .placeholder-content .placeholder-content_item {
    margin-bottom: 12px;
  }
}
@media (max-width:  767px) {
  .placeholder-content .placeholder-filter .box {
      width: 32.6%;
      height: 80px;
  }
  .placeholder-content .placeholder-filter .box:nth-child(3n + 0) {
      margin-right: 0;
  }
  .placeholder-content .placeholder-product_list .placeholder-content_list {
    margin-right: 0;
    width: 100%;
  }
  
}
  </style>
