<?php if($block->isCaptchakey()){ ?>
   <script src="https://www.google.com/recaptcha/api.js"  xml="space"></script>
<?php } ?>
<?php $diamond = $block->getProduct(); $settingcoockieval = array(); $labsettings = false;
if($block->getRingCookieData()){
   $settingcoockieval = $block->getRingCookieData();   
   if($settingcoockieval->Filtermode == 'labsettings'){
      $labsettings = true;
   } else {
      $labsettings = false;
   }
} else {
   $labsettings = false;
} ?>


<?php if(sizeof($diamond['diamondData']) > 0) {



   $diamondid = $diamond['diamondData']['diamondId'];



   $hasvideo = $type = 0;



   



   if(isset($diamond['diamondData']['videoFileName']) && $diamond['diamondData']['videoFileName'] != '') {



      /*$headers = $block->is_404($diamond['diamondData']['videoFileName']);*/

      $headers = 0;



      if(!$headers){

         $url = parse_url($diamond['diamondData']['videoFileName']);
         if(isset($url['scheme'])){

            if($url['scheme'] == 'https'){

               $hasvideo = 1;

               if (strpos($diamond['diamondData']['videoFileName'], '.mp4') !== false) {

                  $type = 1; 

               } else {

                  $type = 2; 

               }

            }
         }
      }



   } else {



     $hasvideo = 0;



   }







   ?>



<?php if(isset($diamond['diamondData']['image1'])){



   $imgurl = $diamond['diamondData']['image1']; 



   }



    ?>



<?php if($diamond['diamondData']['fancyColorMainBody']) { 



   if(!$block->is_404($diamond['diamondData']['colorDiamond'])){



                       $imageurl = $diamond['diamondData']['colorDiamond'];



                     } else if($diamond['diamondData']['defaultDiamondImage']) {
                       $imageurl = $diamond['diamondData']['defaultDiamondImage'];  
                     } else {



                       $imageurl = $this->getViewFileUrl('Gemfind_Ringbuilder::images/no-image.jpg');  



                     }



   } else { 



   if(!$block->is_404($diamond['diamondData']['image2'])){



                       $imageurl = $diamond['diamondData']['image2'];



                     } else if($diamond['diamondData']['defaultDiamondImage']) {
                       $imageurl = $diamond['diamondData']['defaultDiamondImage'];  
                     } else {
                       $imageurl = $this->getViewFileUrl('Gemfind_Diamondsearch::images/no-image.jpg');   
                     } 



   } ?>



<div class="loading-mask gemfind-loading-mask" id="gemfind-loading-mask" style="display: none;">



   <div class="loader gemfind-loader">



      <p>Please wait...</p>



   </div>



</div>



<section class="diamonds-search with-specification diamond-page flow-tabs">



   <div class="tab-section">



      <ul class="tab-ul">

         <?php if($block->checkRingCookie()) { ?>

         <?php if($labsettings){ ?>
         <li class="tab-li"><div><a href="<?php echo $block->getUrl('ringbuilder/settings').'type/labsettings'; ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Setting'); ?></strong></span><i class="ring-icon tab-icon"></i></a></div></li>
		  <?php } else { ?>
			 <li class="tab-li"><div><a href="<?php echo $block->getUrl('ringbuilder/settings'); ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Setting'); ?></strong></span><i class="ring-icon tab-icon"></i></a></div></li>
		  <?php } ?>

         <?php } else { ?>

         <li class="tab-li active"><div><a href="<?php echo $block->getUrl('ringbuilder/diamond'); ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Diamond'); ?></strong></span><i class="diamond-icon tab-icon"></i></a></div></li>         

         <?php } ?>

         <?php if(!$block->checkRingCookie()) { ?>

         <?php if($labsettings){ ?>
         <li class="tab-li"><div><a href="<?php echo $block->getUrl('ringbuilder/settings').'type/labsettings'; ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Setting'); ?></strong></span><i class="ring-icon tab-icon"></i></a></div></li>
		  <?php } else { ?>
			 <li class="tab-li"><div><a href="<?php echo $block->getUrl('ringbuilder/settings'); ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Setting'); ?></strong></span><i class="ring-icon tab-icon"></i></a></div></li>
		  <?php } ?>

         <?php } else { ?>

         <li class="tab-li active"><div><a href="<?php echo $block->getUrl('ringbuilder/diamond'); ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Diamond'); ?></strong></span><i class="diamond-icon tab-icon"></i></a></div></li>

         <?php } ?>

         <li class="tab-li"><div><a href="javascript:;"><span class="tab-title"><?php echo __('Review'); ?><strong><?php echo __('Complete Ring'); ?></strong></span><i class="finalring-icon tab-icon"></i></a></div></li>

      </ul> 

      <!--<ul class="tab-ul">
	   
      
         
		<?php /* if($labsettings){ ?>
         <li class="tab-li"><div><a href="<?php echo $block->getUrl('ringbuilder/settings').'type/labsettings'; ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Setting'); ?></strong></span><i class="ring-icon tab-icon"></i></a></div></li>
		  <?php } else { ?>
			 <li class="tab-li"><div><a href="<?php echo $block->getUrl('ringbuilder/settings'); ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Setting'); ?></strong></span><i class="ring-icon tab-icon"></i></a></div></li>
		  <?php } ?>
		 <li class="tab-li active"><div><a href="<?php echo $block->getUrl('ringbuilder/diamond'); ?>"><span class="tab-title"><?php echo __('Choose Your'); ?><strong><?php echo __('Diamond'); ?></strong></span><i class="diamond-icon tab-icon"></i></a></div></li> 
         <li class="tab-li"><div><a href="javascript:;"><span class="tab-title"><?php echo __('Review'); ?><strong><?php echo __('Complete Ring'); */ ?></strong></span><i class="finalring-icon tab-icon"></i></a></div></li>

      </ul>-->

   </div>



   <div class="d-container">



      <div class="d-row">



         <div class="diamonds-preview no-padding">



            <div class="diamond-info">



               <div class="product-thumb">



                  <?php if(isset($diamond['diamondData']['image1'])){ ?>



                  <div class="thumg-img diamention">



                     <a href="javascript:;" onclick="Imageswitch1(event);">



                     <img src="<?php echo $this->getViewFileUrl('Gemfind_Ringbuilder::images/loader-2.gif'); ?>" data-src="<?php echo $diamond['diamondData']['image1'] ?>" style="width:40px; height: 40px;" alt="<?php echo $diamond['diamondData']['mainHeader'] ?>" title="<?php echo $diamond['diamondData']['mainHeader'] ?>" class="thumbimg" id="thumbimg1" />



                     </a>



                  </div>



                  <?php } ?>



                  <div class="thumg-img" id="thumbdiamondimg">



                     <a href="javascript:;" onclick="Imageswitch2(event);">



                     <img src="<?php echo $this->getViewFileUrl('Gemfind_Diamondsearch::images/loader-2.gif'); ?>"  data-src="<?php echo $imageurl ?>" style="width:40px; height: 40px;" alt="<?php echo $diamond['diamondData']['mainHeader'] ?>" title="<?php echo $diamond['diamondData']['mainHeader'] ?>" class="thumbimg" id="thumbimg2" />



                     </a>



                  </div>



                  <?php if($hasvideo) { ?>



                  <?php if($type == 1){ ?>



                  <div class="thumg-img">



                     <a href="javascript:;" onclick="Videorun(event);">



                     <img style="height: 40px;" src="<?php echo $this->getViewFileUrl('Gemfind_Ringbuilder::images/360-view.png'); ?>" id="img1iframe" class="video"/>



                     </a>



                  </div>



                  <?php } else { ?> 



                  <div class="thumg-img">



                     <a href="javascript:;" onclick="Videorun(event);">



                     <img style="height: 40px;" src="<?php echo $this->getViewFileUrl('Gemfind_Ringbuilder::images/360-view.png'); ?>" id="img1iframe" class="iframe">



                     </a>



                  </div>



                  <?php } ?>



                  <?php } ?>



               </div>



               <div class="diamond-image">



                  <div class="diamondvideo" id="diamondvideo" <?php if(!$hasvideo) { ?> style="display: none;" <?php } ?>>



                     <?php if($type == 1) { ?>

					 <video  playsinline="" autoplay="" loop="" muted="" width="" height="" src="<?php echo $diamond['diamondData']['videoFileName']; ?>" type="video/mp4"></video>



                     <?php } elseif($type == 2) { ?>



                     <iframe src="<?php echo $diamond['diamondData']['videoFileName']; ?>" id="iframevideo" scrolling="no"></iframe> 



                     <?php } else {



                        echo __('No Video');



                        } ?>



                  </div>



                  <div class="diamondimg" id="diamondimg" <?php if($hasvideo) { ?> style="display: none;" <?php } ?>>



                     <img src="<?php echo $this->getViewFileUrl('Gemfind_Diamondsearch::images/loader-2.gif'); ?>" data-src="<?php echo $imageurl; ?>" id="diamondmainimage" alt="<?php echo $diamond['diamondData']['mainHeader'] ?>" title="<?php echo $diamond['diamondData']['mainHeader'] ?>">



                  </div>



               </div>



               <?php 
                  if(isset($block->diamondReport()['data']['show_In_House_Diamonds_First'])){
                     ?><h2 style="text-transform:capitalize;"><?php echo __('Stock Number '); ?><span><?php echo $diamond['diamondData']['stockNumber']; ?></span></h2><?php
                  }
                  else
                  {
                     ?><h2><?php echo __('SKU#'); ?><span><?php echo $diamond['diamondData']['diamondId']; ?></span></h2><?php 
                  }
               ?>


				<?php if(isset($block->diamondReport()['data']['show_Certificate_in_Diamond_Search']) && $block->diamondReport()['data']['show_Certificate_in_Diamond_Search']!="") {?> 
                <div class="diamond-report">
                   <p><b><?php echo __('Diamond Grading Report'); ?></b></p>
                   <?php if ($diamond['diamondData']['certificateUrl']) { ?>
                   <div class="view_text">
                      <a href="javascript:void(0);" onclick="javascript:window.open('<?php echo $diamond['diamondData']['certificateUrl']; ?>','CERTVIEW','scrollbars=yes,resizable=yes,width=860,height=550')"><?php echo __(' View'); ?></a>
                   </div>
                   <?php } else { ?>
                     <?php echo __(' Not Available'); ?>
                  <?php } ?>
                </div>
				<?php }?>

            <?php if(isset($block->diamondReport()['data']['show_Certificate_in_Diamond_Search']) && $block->diamondReport()['data']['show_Certificate_in_Diamond_Search']!="") {?>

               <div class="diamond-grade">



                  <div class="grade-logo">



                     <img src="<?php echo $diamond['diamondData']['certificateIconUrl'] ?>" style="width:94px; height: 94px; max-width:inherit;" alt="<?php echo $diamond['diamondData']['mainHeader'] ?>" title="<?php echo $diamond['diamondData']['mainHeader'] ?>">



                  </div>


                  <?php if ($diamond['diamondData']['certificateUrl']) { ?>
                  <div class="grade-info">



                     <p><?php echo $diamond['diamondData']['subHeader'] ?></p>



                  </div>
                  <?php } else { ?>
                        <p>Not available, please contact retailer.</p>
                     <?php } ?>


               </div>
            <?php }?>


            </div>



            <?php if($diamond['diamondData']['internalUselink'] == 'Yes'){ ?>



            <?php $dealerInfoarray = (array) $diamond['diamondData']['retailerInfo']; ?>



            <div class="internaluse">



               <?php echo __('Internal use Only:'); ?> <a href="javascript:;" id="internaluselink" class="internaluselink" title="<?php echo __('Dealer Info'); ?>"><?php echo __('Click Here'); ?></a> <?php echo __('for Dealer Info.'); ?>



               <div class="auth-section" id="auth-section" style="display: none;">



                  <div class="msg" id="msg"></div>



                  <form class="internaluseform" id="internaluseform" method="post">

                     <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">

                     <input type="password" name="password" value="" placeholder="<?php echo __('Enter Your Gemfind Password'); ?>">



                     <button type="button" onclick="internaluselink()" title="Submit" class="preference-btn">



                     <span><?php echo __('Submit'); ?></span>



                     </button>



                  </form>



               </div>



               <div class="dealer-info-section" id="dealer-info-section" style="display: none;">



                  <table>

                     <tr>

                        <td><?php echo __('Dealer Name:'); ?></td>

                        <td><?php echo ($dealerInfoarray['retailerName'])?$dealerInfoarray['retailerName']:'-'; ?></td>

                     </tr>

                     <tr>

                        <td><?php echo __('Dealer Company:'); ?></td>

                        <td><?php echo ($dealerInfoarray['retailerCompany'])?$dealerInfoarray['retailerCompany']:'-'; ?></td>

                     </tr>

                     <tr>

                        <td><?php echo __('Dealer City/State:'); ?></td>

                        <td><?php echo ($dealerInfoarray['retailerCity'])?$dealerInfoarray['retailerCity']:''; ?>/<?php echo ($dealerInfoarray['retailerState'])?$dealerInfoarray['retailerState']:''; ?></td>

                     </tr>

                     <tr>

                        <td><?php echo __('Dealer Contact No.:'); ?></td>

                        <td><?php echo ($dealerInfoarray['retailerContactNo'])?$dealerInfoarray['retailerContactNo']:'-'; ?></td>

                     </tr>

                     <tr>

                        <td><?php echo __('Dealer Email:'); ?></td>

                        <td><?php echo ($dealerInfoarray['retailerEmail'])?$dealerInfoarray['retailerEmail']:'-'; ?></td>

                     </tr>

                     <tr>

                        <td><?php echo __('Dealer Lot number of the item:'); ?></td>

                        <td><?php echo ($dealerInfoarray['retailerLotNo'])?$dealerInfoarray['retailerLotNo']:'-'; ?></td>

                     </tr>

                     <tr>

                        <td><?php echo __('Dealer Stock number of the item:'); ?></td>

                        <td><?php echo ($dealerInfoarray['retailerStockNo'])?$dealerInfoarray['retailerStockNo']:'-'; ?></td>

                     </tr>

                     <tr>

                        <td><?php echo __('Wholesale Price:'); ?></td>

                        <td><?php if($diamond['diamondData']['wholeSalePrice']){
                           if($diamond['diamondData']['currencyFrom'] != 'USD'){
                              echo $diamond['diamondData']['currencyFrom'];
                           }
                           echo $diamond['diamondData']['currencySymbol'].$diamond['diamondData']['wholeSalePrice'];
                        } else {
                           echo '-';
                        }
                         ?></td>

                     </tr>

                     <tr>

                        <td><?php echo __('Third Party:'); ?></td>

                        <td><?php echo ($dealerInfoarray['thirdParty'])?$dealerInfoarray['thirdParty']:'-'; ?></td>

                     </tr>

                     <tr>

                        <td><?php echo __('Diamond Id:'); ?></td>

                        <td><?php echo ($dealerInfoarray['diamondID'])?$dealerInfoarray['diamondID']:'-'; ?></td>

                     </tr>

                     <tr>

                        <td><?php echo __('Seller Name:'); ?></td>

                        <td><?php echo ($dealerInfoarray['sellerName'])?$dealerInfoarray['sellerName']:'-'; ?></td>

                     </tr>

                     <tr>

                        <td><?php echo __('Seller Address:'); ?></td>

                        <td><?php echo ($dealerInfoarray['sellerAddress'])?$dealerInfoarray['sellerAddress']:'-'; ?></td>

                     </tr>

                     <tr>

                        <td><?php echo __('Dealer Fax:'); ?></td>

                        <td><?php echo ($dealerInfoarray['retailerFax'])?$dealerInfoarray['retailerFax']:'-'; ?></td>

                     </tr>

                     <tr>

                        <td><?php echo __('Dealer Address:'); ?></td>

                        <td><?php echo ($dealerInfoarray['retailerAddress'])?$dealerInfoarray['retailerAddress']:'-'; ?></td>

                     </tr>

                  </table>



               </div>



            </div>



            <?php } ?>



         </div>



         <div class="diamonds-details no-padding diamond-request-form">



            <div class="diamond-data" id="diamond-data">



               <div class="specification-title">



                  <h2><?php echo $diamond['diamondData']['mainHeader'] ?></h2>



                  <h4 class="diamond-spec-header">



                     <a href="javascript:;" id="spcfctn" onclick="CallSpecification();">



                        <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"



                           width="20px" height="20px" viewBox="0 0 612 612" style="enable-background:new 0 0 612 612;" xml:space="preserve">



                           <g>



                              <g id="New_x5F_Post">



                                 <g>



                                    <path d="M545.062,286.875c-15.854,0-28.688,12.852-28.688,28.688v239.062h-459v-459h239.062



                                       c15.854,0,28.688-12.852,28.688-28.688S312.292,38.25,296.438,38.25H38.25C17.136,38.25,0,55.367,0,76.5v497.25



                                       C0,594.883,17.136,612,38.25,612H535.5c21.114,0,38.25-17.117,38.25-38.25V315.562



                                       C573.75,299.727,560.917,286.875,545.062,286.875z M605.325,88.95L523.03,6.655C518.556,2.18,512.684,0,506.812,0



                                       s-11.743,2.18-16.218,6.675l-318.47,318.45v114.75h114.75l318.45-318.45c4.494-4.495,6.675-10.366,6.675-16.237



                                       C612,99.297,609.819,93.445,605.325,88.95z M267.75,382.5H229.5v-38.25L506.812,66.938l38.25,38.25L267.75,382.5z"/>



                                 </g>



                              </g>



                           </g>



                        </svg>

                        <span class="diamond_spec" onclick="CallSpecification();"><?php echo __('Diamond Specification'); ?></span>

                     </a>



                  </h4>



               </div>



               <div class="diamond-content-data" id="diamond-content-data">

                  <?php if(isset($block->diamondReport()['data']['show_Certificate_in_Diamond_Search']) && $block->diamondReport()['data']['show_Certificate_in_Diamond_Search']!='') {?>

                  <div class="diamond-desc">



                     <p><?php echo $diamond['diamondData']['subHeader'] ?></p>



                  </div>
                  <?php } ?>


                  <div class="form-field diamonds-info">



                     <div class="intro-field">



                        <ul>



                           <li>



                              <strong><?php echo __('Color:') ?></strong>



                              <p><?php if($diamond['diamondData']['color'] != '') { 
                                 if ( $diamond['diamondData']['fancyColorMainBody'] ) {
                                   $color_to_display = $diamond['diamondData']['fancyColorIntensity'].' '.$diamond['diamondData']['fancyColorMainBody'];
                                 } else {
                                   $color_to_display = $diamond['diamondData']['color'];
                                 }
                                 echo $color_to_display; 
                              } else { echo __('NA'); } ?></p>



                           </li>



                           <li>



                              <strong><?php echo __('Clarity:') ?></strong>



                              <p><?php if($diamond['diamondData']['clarity'] != '') { echo $diamond['diamondData']['clarity']; } else { echo __('NA'); } ?></p>



                           </li>



                        </ul>

                        <ul>

                           <?php if(isset($block->diamondReport()['data']['show_Certificate_in_Diamond_Search']) && $block->diamondReport()['data']['show_Certificate_in_Diamond_Search']!='') {?>

                           <li>



                              <strong><?php echo __('Report:') ?></strong>



                              <p><?php if($diamond['diamondData']['certificate'] != '') { echo $diamond['diamondData']['certificate']; } else { echo __('NA'); } ?></p>



                           </li>

                        <?php } ?>

                           <li>



                              <strong><?php echo __('Cut:') ?></strong>



                              <p><?php if($diamond['diamondData']['cut'] != '') { echo $diamond['diamondData']['cut']; } else { echo __('NA'); } ?></p>



                           </li>



                        </ul>



                     </div>



                     <div class="product-controler">



                        <ul>



                           <?php if ($block->isHintEnabled() == 1): ?>



                           <li><a href="javascript:;" class="showForm" onclick="CallShowform(event);" data-target="drop-hint-main"><?php echo __('Drop A Hint');?></a></li>



                           <?php endif; ?>



                           <?php if ($block->isMoreInfoEnabled() == 1): ?>



                           <li><a href="javascript:;" class="showForm" onclick="CallShowform(event);" data-target="req-info-main"><?php echo __('Request More Info');?></a></li>



                           <?php endif; ?>



                           <?php if ($block->isEmailtoFriendEnabled() == 1): ?>



                           <li><a href="javascript:;" class="showForm" onclick="CallShowform(event);" data-target="email-friend-main"><?php echo __('E-Mail A Friend');?></a></li>



                           <?php endif; ?>



                           <?php if ($block->isPrintDetailEnabled() == 1): ?>



                           <li><a href="javascript:;" data="<?php echo $this->getViewFileUrl('Gemfind_Ringbuilder::images/print_icon.gif'); ?>" class="prinddia" id="prinddia" ><?php echo __('Print Details') ?></a></li>



                           <?php endif; ?>



                           <?php if ($block->isScheduleViewingEnabled() == 1): ?>



                           <li><a href="javascript:;" class="showForm" onclick="CallShowform(event);" data-target="schedule-view-main"><?php echo __('Schedule Viewing');?></a></li>



                           <?php endif; ?>



                        </ul>



                     </div>



                     <div class="diamond-action">

                     <?php if($diamond['diamondData']['showPrice']){ ?>

                        <span><?php if($diamond['diamondData']['currencyFrom'] != 'USD'){ echo $diamond['diamondData']['currencyFrom'];} echo $diamond['diamondData']['currencySymbol'].number_format($diamond['diamondData']['fltPrice']); ?></span>

                     <?php } else { ?>
                        <span><?php echo __('Call For Price'); ?></span>
                     <?php } ?>

                        <?php 

                        if($block->getRingCaratCookieData()){

                           $setting = $block->getRingCaratCookieData();



                           if($setting->caratmin > '0.00'){



                              $TempCaratMin = ($setting->caratmin * 10) / 100;



                              $CaratMin = ($setting->caratmin - $TempCaratMin);



                           } else {

                              $CaratMin = $diamond['diamondData']['caratWeight'];



                           }



                            if($setting->caratmax > '0.00'){



                              $TempCaratMax = ($setting->caratmax * 10) / 100;



                              $CaratMax = ($setting->caratmax + $TempCaratMax);



                           } else {



                              $CaratMax = $setting->caratmax;



                           }



                           if($diamond['diamondData']['caratWeight'] > $CaratMax || $diamond['diamondData']['caratWeight'] < $CaratMin){ ?>

                              <div><p style="color: red;"><?php echo _('This diamond will not properly fit with selected setting.'); ?></p></div>

                        <?php } } ?>

                        <form action="<?php echo $block->getSubmitUrl($diamond['diamondData']['diamondId']); ?>" method="post" id="product_addtocart_form">
                           <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
                           <?php if(isset($diamond['diamondData']['type'])){ ?>
                              <input type="hidden" name="type" value="<?php echo $diamond['diamondData']['type']; ?>">   
                           <?php } ?>

                           <?php if($diamond['diamondData']['showPrice'] && $diamond['diamondData']['dsEcommerce']){ ?>
                           <div class="box-tocart">



                              <button type="submit" title="Buy Diamond Only" class="addtocart tocart" onclick="showLoader();" id="product-addtocart-button"><?php echo __('Buy Diamond Only')?></button>



                           </div>

                           <?php } ?>

                        </form>





                        <form action="<?php echo $block->getAddDiamondUrl($diamond['diamondData']['diamondId']); ?>" method="post" id="completering_addtocart_form">

                           <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">

                           <div class="box-tocart">

                              <input type="hidden" name="centerstone" id="centerstone" value="<?php echo $diamond['diamondData']['shape'] ?>" />

                              <input type="hidden" name="carat" id="carat" value="<?php echo $diamond['diamondData']['caratWeight'] ?>" />

                              <?php if(isset($diamond['diamondData']['type'])){ ?>
                              <input type="hidden" name="type" value="<?php echo $diamond['diamondData']['type']; ?>">   
                           <?php } ?>

                           <?php if($block->checkRingCookie()) { ?>

                                 <button type="submit" title="Complete Your Ring" class="addtocart tocart" onclick="showLoader();" id="completering_addtocart_button"><?php echo __('Complete Your Ring')?></button>

                           <?php } else { ?>

                                 

                                 <button type="submit" title="Add Your Setting" class="addtocart tocart" onclick="showLoader();" id="completering_addtocart_button"><?php echo __('Add Your Setting')?></button>

                           <?php } ?>

                              



                           </div>



                        </form>



                     </div>

					<?php 
                  if(isset($diamond['diamondData']['shape'])){
                    $urlshape = str_replace(' ', '-',$diamond['diamondData']['shape']).'-shape-';
                  }else {
                    $urlshape = '';
                  }
                  if(isset($diamond['diamondData']['caratWeight'])){
                    $urlcarat = str_replace(' ', '-',$diamond['diamondData']['caratWeight']).'-carat-';
                  }else {
                    $urlcarat = '';
                  }
                  if(isset($diamond['diamondData']['color'])){
                    $urlcolor = str_replace(' ', '-',$diamond['diamondData']['color']).'-color-';
                  } else {
                    $urlcolor = '';
                  }
                  if(isset($diamond['diamondData']['clarity'])){
                    $urlclarity = str_replace(' ', '-',$diamond['diamondData']['clarity']).'-clarity-';
                  }else{
                    $urlclarity = '';
                  }
                  if(isset($diamond['diamondData']['cut'])){
                    $urlcut = str_replace(' ', '-',$diamond['diamondData']['cut']).'-cut-';
                  }else{
                    $urlcut = '';
                  }
                  if(isset($diamond['diamondData']['certificate'])){
                    $urlcert = str_replace(' ', '-',$diamond['diamondData']['certificate']).'-certificate-';
                  }else{
                    $urlcert = '';
                  }
                  $urlstring = strtolower($urlshape.$urlcarat.$urlcolor.$urlclarity.$urlcut.$urlcert.'sku-'.$diamond['diamondData']['diamondId']);
                  $diamondviewurl = ''; 
                  if(isset($diamond['diamondData']['type'])){
                     $dimaondtype = 'type/labcreated';
                  } else{
                     $dimaondtype = '';
                  }
                  $diamondviewurl = $block->getDiamondUrl($urlstring).$dimaondtype;              


               ?>
			   <ul class="list-inline social-share">
							<div id="fb-root"></div>
							<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v9.0" nonce="rmlivbf3"></script>
							<script async  src="https://assets.pinterest.com/js/pinit_main.js?0.6285343628670037"></script>
							<?php if(isset($block->diamondReport()['data']['show_Pinterest_Share']) && $block->diamondReport()['data']['show_Pinterest_Share']!='') { ?>
							<li class="save_pinterest">
								<a class="save_pint" data-pin-do="buttonPin" href="https://www.pinterest.com/pin/create/button/?url=<?php echo $diamondviewurl;?>&media=<?php echo $imageurl; ?>&description=<?php echo $diamond['diamondData']['subHeader'] ?>" data-pin-height="28"></a>
							</li>
							<?php } ?>
							<?php if(isset($block->diamondReport()['data']['show_Twitter_Share']) && $block->diamondReport()['data']['show_Twitter_Share']!='') { ?>
							<li class="share_tweet">
								<a href="https://twitter.com/share?ref_src=<?php echo $diamondviewurl;?>" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
							</li>
							<?php } ?>
							<?php if(isset($block->diamondReport()['data']['show_Facebook_Share']) && $block->diamondReport()['data']['show_Facebook_Share']!='') { ?>
							<li class="share_fb">
								<div class="fb-share-button" data-href="<?php echo $diamondviewurl;?>" data-layout="button" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $diamondviewurl;?>" class="fb-xfbml-parse-ignore">Share</a></div>
							</li>
							<?php } ?>
							<?php if(isset($block->diamondReport()['data']['show_Facebook_Like']) && $block->diamondReport()['data']['show_Facebook_Like']!='') { ?>
							<li class="like_fb">
								<div class="fb-like" data-href="<?php echo $diamondviewurl;?>" data-width="" data-layout="button_count" data-share="false" data-action="like" data-size="small" ></div>
							</li>
							<?php } ?>
					</ul> 

                  </div>



               </div>



               <div class="diamond-forms">



                  <?php if ($block->isHintEnabled() == 1): ?>

                  

                  <div class="form-main no-padding diamond-request-form cls-for-hide" id="drop-hint-main">



                     <div class="requested-form">



                        <h2><?php echo __('Drop A Hint');?></h2>



                        <p><?php echo __('Because you deserve this.');?></p>



                     </div>



                     <div class="note" style="display: none;"></div>



                     <form method="post" enctype="multipart/form-data"



                        data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"



                        data-mage-init='{"validation":{}}'  class="form-drop-hint" id="form-drop-hint">

                        <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">

                        <input name="diamondurl" type="hidden" value="<?php echo $block->getRequest()->getUriString(); ?>">

                        <?php if(isset($diamond['diamondData']['type'])){ ?>
                           <input type="hidden" name="type" value="<?php echo $diamond['diamondData']['type']; ?>">   
                        <?php } ?>

                        <input name="diamondid" type="hidden" value="<?php echo $diamond['diamondData']['diamondId']; ?>">



                        <div class="form-field">



                           <label>



                           <input name="name" id="drophint_name" onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" type="text" class="" data-validate="{required:true}" placeholder=" ">



                           <span><?php echo __('Your Name');?></span>



                           </label>



                           <label>



                           <input name="email" id="drophint_email" onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" type="email" class="" data-validate="{required:true, 'validate-email':true}" placeholder=" ">



                           <span><?php echo __('Your E-mail');?></span>



                           </label>



                           <label>



                           <input name="recipient_name" id="drophint_rec_name" onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" type="text" class="" data-validate="{required:true}" placeholder=" ">



                           <span><?php echo __('Hint Recipient\'s Name');?></span>



                           </label>



                           <label>



                           <input name="recipient_email" id="drophint_rec_email" onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" type="email" class="" data-validate="{required:true, 'validate-email':true}" placeholder=" ">



                           <span><?php echo __('Hint Recipient\'s E-mail');?></span>



                           </label>



                           <label>



                           <input name="gift_reason" id="gift_reason" onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" type="text" class="" data-validate="{required:true}" placeholder=" ">



                           <span><?php echo __('Reason For This Gift');?></span>



                           </label>



                           <label>



                           <textarea name="hint_message" rows="2" cols="20" id="drophint_message" class="" data-validate="{required:true}" placeholder="Add A Personal Message Here ..."></textarea>



                           </label>



                           <label>



                              <div class="has-datepicker--icon">



                                 <input name="gift_deadline" id="gift_deadline" autocomplete="false" readonly title="Gift Deadline" value="" type="text" data-validate="{required:true}" placeholder="Gift Deadline">



                              </div>



                           </label>

                              <?php if($block->isCaptchakey()){ ?>
                              <div class="form-group required">   
                                 <div class="g-recaptcha required" id="recaptcha"
                                        data-sitekey="<?php echo $block->isCaptchakey(); ?>">
                                 </div>
                                 <div style="display:none" id="error-msg">
                                    <span><?php echo __('This is a required field.') ?></span>
                                 </div>
                              </div>
                              <?php } ?>

                           <div class="prefrence-action">



                              <div class=" prefrence-action action">



                                 <button type="button" data-target="drop-hint-main" onclick="Closeform(event);" class="cancel preference-btn btn-cencel"><span><?php echo __('Cancel');?></span></button>



                                 <button type="button" onclick="formSubmit(event,'<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>','form-drop-hint')" title="Submit" class="preference-btn">



                                 <span><?php echo __('Drop Hint');?></span>



                                 </button>



                              </div>



                           </div>



                        </div>



                     </form>



                  </div>



                  <?php endif; ?>



                  <?php if ($block->isEmailtoFriendEnabled() == 1): ?>



                  <div class="form-main no-padding diamond-request-form cls-for-hide" id="email-friend-main">



                     <div class="requested-form">



                        <h2><?php echo __('E-Mail A Friend');?></h2>



                     </div>



                     <div class="note" style="display: none;"></div>



                     <form method="post" enctype="multipart/form-data"



                        data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"



                        data-mage-init='{"validation":{}}'  class="form-email-friend" id="form-email-friend">

                        <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">

                        <input name="diamondurl" type="hidden" value="<?php echo $block->getRequest()->getUriString(); ?>">

                        <?php if(isset($diamond['diamondData']['type'])){ ?>
                           <input type="hidden" name="type" value="<?php echo $diamond['diamondData']['type']; ?>">   
                        <?php } ?>

                        <input name="diamondid" type="hidden" value="<?php echo $diamond['diamondData']['diamondId']; ?>">



                        <div class="form-field">



                           <label>



                           <input id="email_frnd_name" name="name" onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" placeholder=""  type="text" class="" data-validate="{required:true}">



                           <span for="email_frnd_name"><?php echo __('Your Name');?></span>



                           </label>



                           <label>



                           <input name="email" type="email"  onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" placeholder=""  id="email_frnd_email" class="" data-validate="{required:true}">



                           <span><?php echo __('Your E-mail');?></span>



                           </label>



                           <label>



                           <input name="friend_name" type="text" onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" placeholder="" id="email_frnd_fname" class="" data-validate="{required:true}">



                           <span><?php echo __('Your Friend\'s Name');?></span>



                           </label>



                           <label>



                           <input name="friend_email" type="email" onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" placeholder=""  id="email_frnd_femail" class="" data-validate="{required:true}">



                           <span><?php echo __('Your Friend\'s E-mail');?></span>



                           </label>



                           <label>



                           <textarea name="message" rows="2" placeholder="Add A Personal Message Here ..."  cols="20" id="email_frnd_message" class="" data-validate="{required:true}"></textarea>



                           </label>

                              <?php if($block->isCaptchakey()){ ?>
                              <div class="form-group required">   
                                 <div class="g-recaptcha required" id="recaptcha1"
                                        data-sitekey="<?php echo $block->isCaptchakey(); ?>">
                                 </div>
                                 <div style="display:none" id="error-msg">
                                    <span><?php echo __('This is a required field.') ?></span>
                                 </div>
                              </div>
                              <?php } ?>

                           <div class="prefrence-action">



                              <div class=" prefrence-action action">



                                 <button type="button" data-target="email-friend-main" onclick="Closeform(event);" class="cancel preference-btn btn-cencel"><span><?php echo __('Cancel');?></span></button>



                                 <button type="button" onclick="formSubmit(event,'<?php /* @escapeNotVerified */ echo $block->getEmailFrndFormAction(); ?>','form-email-friend')" title="Submit" class="preference-btn">



                                 <span><?php echo __('Send To Friend');?></span>



                                 </button>



                              </div>



                           </div>



                        </div>



                     </form>



                  </div>



                  <?php endif; ?>



                  <?php if ($block->isMoreInfoEnabled() == 1): ?>



                  <div class="form-main no-padding diamond-request-form cls-for-hide" id="req-info-main">



                     <div class="requested-form">



                        <h2><?php echo __('Request More Information');?></h2>



                        <p><?php echo __('Our specialists will contact you.');?></p>



                     </div>



                     <div class="note" style="display: none;"></div>



                     <form method="post" enctype="multipart/form-data"



                        data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"



                        data-mage-init='{"validation":{}}'  class="form-request-info" id="form-request-info">

                        <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">

                        <input name="diamondurl" type="hidden" value="<?php echo $block->getRequest()->getUriString(); ?>">
                        
                        <?php if(isset($diamond['diamondData']['type'])){ ?>
                           <input type="hidden" name="type" value="<?php echo $diamond['diamondData']['type']; ?>">   
                        <?php } ?>

                        <input name="diamondid" type="hidden" value="<?php echo $diamond['diamondData']['diamondId']; ?>">



                        <div class="form-field">



                           <label>



                           <input name="name" type="text" onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" id="reqinfo_name" placeholder=""  class="" data-validate="{required:true}">



                           <span><?php echo __('Your Name');?></span>



                           </label>



                           <label>



                           <input name="email" type="email" onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" id="reqinfo_email" placeholder=""  class="" data-validate="{required:true}">



                           <span><?php echo __('Your E-mail Address');?></span>



                           </label>



                           <label>



                           <input name="phone" type="text" onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" id="reqinfo_phone" placeholder=""  class="" data-validate="{required:true}">



                           <span><?php echo __('Your Phone Number');?></span>



                           </label>



                           <label>



                           <textarea name="hint_message" rows="2" cols="20" placeholder="Add A Personal Message Here ..."  id="reqinfo_message" class="" data-validate="{required:true}"></textarea>



                           </label>



                           <div class="prefrence-area">



                              <p><?php echo __('Contact Preference:');?></p>



                              <ul>



                                 <li>



                                    <input type="radio" data-validate="{'validate-one-required-by-name':true}" class="radio required-entry"  name="contact_pref" value="By Email">



                                    <label><?php echo __('By Email');?></label>



                                 </li>



                                 <li>



                                    <input type="radio" data-validate="{'validate-one-required-by-name':true}" class="radio required-entry"  name="contact_pref" value="By Phone">



                                    <label><?php echo __('By Phone');?></label>



                                 </li>



                              </ul>

                              <?php if($block->isCaptchakey()){ ?>
                              <div class="form-group required">   
                                 <div class="g-recaptcha required" id="recaptcha2"
                                        data-sitekey="<?php echo $block->isCaptchakey(); ?>">
                                 </div>
                                 <div style="display:none" id="error-msg">
                                    <span><?php echo __('This is a required field.') ?></span>
                                 </div>
                              </div>
                              <?php } ?>

                              <div class="prefrence-action">



                                 <div class=" prefrence-action action">



                                    <button type="button" data-target="req-info-main" onclick="Closeform(event);" class="cancel preference-btn btn-cencel">



                                    <span><?php echo __('Cancel');?></span>



                                    </button>



                                    <button type="button" onclick="formSubmit(event,'<?php /* @escapeNotVerified */ echo $block->getReqInfoFormAction(); ?>','form-request-info')" title="Submit" class="preference-btn">



                                    <span><?php echo __('Request');?></span>



                                    </button>



                                 </div>



                              </div>



                           </div>



                        </div>



                     </form>



                  </div>



                  <?php endif; ?>



                  <?php if ($block->isScheduleViewingEnabled() == 1): ?>



                  <div class="form-main no-padding diamond-request-form cls-for-hide" id="schedule-view-main">



                     <div class="requested-form">



                        <h2><?php echo __('Schedule A Viewing');?></h2>



                        <p><?php echo __('See This Item & More In Our Store');?></p>



                     </div>



                     <div class="note" style="display: none;"></div>



                     <form method="post" enctype="multipart/form-data"



                        data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"



                        data-mage-init='{"validation":{}}'  class="form-schedule-view" id="form-schedule-view">

                        <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">

                        <input name="diamondurl" type="hidden" value="<?php echo $block->getRequest()->getUriString(); ?>">

                        <?php if(isset($diamond['diamondData']['type'])){ ?>
                           <input type="hidden" name="type" value="<?php echo $diamond['diamondData']['type']; ?>">   
                        <?php } ?>

                        <input name="diamondid" type="hidden" value="<?php echo $diamond['diamondData']['diamondId']; ?>">



                        <div class="form-field">



                           <label>



                           <input name="name" type="text" onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" id="schview_name" placeholder=""  class="" data-validate="{required:true}">



                           <span><?php echo __('Your Name');?></span>



                           </label>



                           <label>



                           <input name="email" type="email" onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" id="schview_email" placeholder=""  class="" data-validate="{required:true}">



                           <span><?php echo __('Your E-mail Address');?></span>



                           </label>



                           <label>



                           <input name="phone" type="text" onfocus="focusFunction(this)" onfocusout="focusoutFunction(this)" id="schview_phone" placeholder=""  class="" data-validate="{required:true}">



                           <span><?php echo __('Your Phone Number');?></span>



                           </label>



                           <label>



                           <textarea name="hint_message" rows="2" cols="20" placeholder="Add A Personal Message Here ..."  id="schview_message" class="" data-validate="{required:true}"></textarea>



                           </label>



                           <label>
                              <select data-validate="{required:true}" name="location"  placeholder=""  id="schview_loc">
                                 <option value=""><?php echo __('--Location--'); ?></option>
                                 <?php $retailerInfo = (array) $diamond['diamondData']['retailerInfo'];
                                       $addressList  = (array) $retailerInfo['addressList']; ?>
                                 <?php foreach ($addressList as $value) { $value = (array) $value; ?>   
                                 <option data-locationid="<?php echo $value['locationID']; ?>" value="<?php echo $value['locationName']; ?>"><?php echo $value['locationName']; ?></option>
                                 <?php } ?>
                              </select>
                           </label>
                           <label>
                              <div class="has-datepicker--icon">
                                 <input name="avail_date" id="avail_date" readonly autocomplete="false" placeholder="When are you avilable?"  title="When are you avilable?" value="" type="text" data-validate="{required:true}">
                              </div>
                           </label>
                          <?php
                     /*echo "<pre>";
                     print_r((array) $retailerInfo['timingList']);*/
                     $timingListArr = (array)$retailerInfo['timingList'];
                     if(empty($timingListArr)) 
                     {
                        ?>
                        <label class="timing_not_avail" style="display:none;">Slots not available on selected date</label>
                        <?php
                     }
                     else
                     {
                        $timingDays = $dayStatusArr = array();
                        foreach($timingListArr as $key => $timingList){
                           
                              $timingDays[0] = array(
                                 "sundayStart" => $timingList->sundayStart,
                                 "sundayEnd" => $timingList->sundayEnd
                              );
                              $timingDays[1] = array(
                                 "mondayStart" => $timingList->mondayStart,
                                 "mondayEnd" => $timingList->mondayEnd
                              );
                              $timingDays[2] = array(
                                 "tuesdayStart" => $timingList->tuesdayStart,
                                 "tuesdayEnd" => $timingList->tuesdayEnd
                              );
                              $timingDays[3] = array(
                                 "wednesdayStart" => $timingList->wednesdayStart,
                                 "wednesdayEnd" => $timingList->wednesdayEnd
                              );
                              $timingDays[4] = array(
                                 "thursdayStart" => $timingList->thursdayStart,
                                 "thursdayEnd" => $timingList->thursdayEnd
                              );
                              $timingDays[5] = array(
                                 "fridayStart" => $timingList->fridayStart,
                                 "fridayEnd" => $timingList->fridayEnd
                              );
                              $timingDays[6] = array(
                                 "saturdayStart" => $timingList->saturdayStart,
                                 "saturdayEnd" => $timingList->saturdayEnd
                              );
                              if($timingList->storeClosedSun == "Yes")
                              {
                                 $dayStatusArr[0] = 0;
                              }
                              if($timingList->storeClosedMon == "Yes")
                              {
                                 $dayStatusArr[1] = 1;
                              }
                              if($timingList->storeClosedTue == "Yes")
                              {
                                 $dayStatusArr[2] = 2;
                              }
                              if($timingList->storeClosedWed == "Yes")
                              {
                                 $dayStatusArr[3] = 3;
                              }
                              if($timingList->storeClosedThu == "Yes")
                              {
                                 $dayStatusArr[4] = 4;
                              }
                              if($timingList->storeClosedFri == "Yes")
                              {
                                 $dayStatusArr[5] = 5;
                              }
                              if($timingList->storeClosedSat == "Yes")
                              {
                                 $dayStatusArr[6] = 6;
                              }


                              ?>
                              <span class="timing_days" data-location="<?php echo $timingList->locationID;?>" style="display:none;"><?php echo json_encode($timingDays);?></span>
                              <?php
                               
                              foreach($dayStatusArr as $key => $value)
                              {
                                 ?>
                                 <span style="display:none;" class="day_status_arr"><?php echo $value;?></span>
                                 <?php
                              }  
                           }
                        ?>
                        <label>
                          <select id="appnt_time" class=""  placeholder=""  name="appnt_time" style="display:none;"></select>
                        </label>
                        <?php
                        ?>
                     <?php } ?>


                              <?php if($block->isCaptchakey()){ ?>
                              <div class="form-group required">   
                                 <div class="g-recaptcha required" id="recaptcha3"
                                        data-sitekey="<?php echo $block->isCaptchakey(); ?>">
                                 </div>
                                 <div style="display:none" id="error-msg">
                                    <span><?php echo __('This is a required field.') ?></span>
                                 </div>
                              </div>
                              <?php } ?>
                           <div class="prefrence-action">



                              <div class=" prefrence-action action">



                                 <button type="button" data-target="schedule-view-main" onclick="Closeform(event);" class="cancel preference-btn btn-cencel"><span><?php echo __('Cancel');?></span></button>



                                 <button type="button" onclick="formSubmit(event,'<?php /* @escapeNotVerified */ echo $block->getScheViewFormAction(); ?>','form-schedule-view')" title="Submit" class="preference-btn">



                                 <span><?php echo __('Request');?></span>



                                 </button>



                              </div>



                           </div>



                        </div>



                     </form>



                  </div>



                  <?php endif; ?>



               </div>



            </div>



            <div class="diamond-specification cls-for-hide" id="diamond-specification">



               <div class="specification-info">



                  <div class="specification-title">



                     <h2><?php echo __('Diamond Details') ?></h2>



                     <h4 class="close">



                        <a href="javascript:;" id="dmnddtl" onclick="CallDiamondDetail();">



                           <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"

                                 viewBox="0 0 52 52" width="20px" height="20px" style="enable-background:new 0 0 52 52;display: inline;vertical-align: text-bottom;" xml:space="preserve">

                              <g>

                                 <path d="M26,0C11.664,0,0,11.663,0,26s11.664,26,26,26s26-11.663,26-26S40.336,0,26,0z M26,50C12.767,50,2,39.233,2,26

                                       S12.767,2,26,2s24,10.767,24,24S39.233,50,26,50z"/>

                                 <path d="M35.707,16.293c-0.391-0.391-1.023-0.391-1.414,0L26,24.586l-8.293-8.293c-0.391-0.391-1.023-0.391-1.414,0

                                    s-0.391,1.023,0,1.414L24.586,26l-8.293,8.293c-0.391,0.391-0.391,1.023,0,1.414C16.488,35.902,16.744,36,17,36

                                    s0.512-0.098,0.707-0.293L26,27.414l8.293,8.293C34.488,35.902,34.744,36,35,36s0.512-0.098,0.707-0.293

                                    c0.391-0.391,0.391-1.023,0-1.414L27.414,26l8.293-8.293C36.098,17.316,36.098,16.684,35.707,16.293z"/>

                              </g>

                           </svg>

                        </a>



                     </h4>



                  </div>



                  <ul>



                     <?php if(isset($diamond['diamondData']['diamondId'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Stock Number') ?></p>



                        </div>



                        <div class="diamonds-info">

                           <?php 
                              if(isset($block->diamondReport()['data']['show_In_House_Diamonds_First']))
                              {
                                 ?><p><?php echo $diamond['diamondData']['stockNumber'] ?></p><?php
                              }
                              else
                              {
                                 ?><p><?php echo $diamond['diamondData']['diamondId'] ?></p><?php 
                              }
                           ?>


                        </div>



                     </li>



                     <?php } ?>



                     <?php if(isset($diamond['diamondData']['fltPrice'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Price') ?></p>



                        </div>



                        <div class="diamonds-info">


                        <?php if($diamond['diamondData']['showPrice']){ ?>
                           <p><?php if($diamond['diamondData']['currencyFrom'] != 'USD'){ echo $diamond['diamondData']['currencyFrom'];} echo $diamond['diamondData']['currencySymbol'].number_format($diamond['diamondData']['fltPrice']); ?></p>
                        <?php } else { ?> 
                           <p><?php echo __('Call For Price'); ?></p>
                        <?php } ?>

                        </div>



                     </li>



                     <?php } ?>

                  <?php if($diamond['diamondData']['showPrice']){ ?>

                     <?php if(isset($diamond['diamondData']['fltPrice'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Price Per Carat') ?></p>



                        </div>



                        <div class="diamonds-info">



                           <?php if(isset($diamond['diamondData']['caratWeight'])) { 



                              $percarat = str_replace(',', '', $diamond['diamondData']['fltPrice'])/$diamond['diamondData']['caratWeight'];



                              ?>



                           <p><?php  if($diamond['diamondData']['currencyFrom'] != 'USD'){ echo $diamond['diamondData']['currencyFrom'];} echo $diamond['diamondData']['currencySymbol'].number_format($percarat,2); ?></p>



                           <?php } else { ?>



                           <p><?php  if($diamond['diamondData']['currencyFrom'] != 'USD'){ echo $diamond['diamondData']['currencyFrom'];} echo $diamond['diamondData']['currencySymbol'].number_format($diamond['diamondData']['fltPrice']); ?></p>



                           <?php } ?>



                        </div>



                     </li>



                     <?php } ?>
                  <?php } else { ?>
                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Price Per Carat') ?></p>



                        </div>



                        <div class="diamonds-info">




                           <p><?php echo __('Call For Price'); ?></p>



                        </div>



                     </li>
                  <?php } ?>



                     <?php if(isset($diamond['diamondData']['caratWeight'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Carat Weight') ?></p>



                        </div>



                        <div class="diamonds-info">



                           <p><?php echo $diamond['diamondData']['caratWeight'] ?></p>



                        </div>



                     </li>



                     <?php } ?>
                     <?php if(isset($diamond['diamondData']['inhouse'])) { ?>
                     <li>
                        <div class="diamonds-details-title">
                           <p><?php echo __('In House') ?></p>
                        </div>
                        <div class="diamonds-info">
                           <p><?php echo $diamond['diamondData']['inhouse'] ?></p>
                        </div>
                     </li>
                     <?php } ?>



                     <?php if(isset($diamond['diamondData']['cut'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Cut') ?></p>



                        </div>



                        <div class="diamonds-info">



                           <p><?php echo $diamond['diamondData']['cut'] ?></p>



                        </div>



                     </li>



                     <?php } ?>



                     <?php if(isset($diamond['diamondData']['color'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Color') ?></p>



                        </div>



                        <div class="diamonds-info">
                           <?php 
                              if ( $diamond['diamondData']['fancyColorMainBody'] ) {
                                $color_to_display = $diamond['diamondData']['fancyColorIntensity'].' '.$diamond['diamondData']['fancyColorMainBody'];
                              } else {
                                $color_to_display = $diamond['diamondData']['color'];
                              }
                           ?>
                           <p><?php echo $color_to_display ?></p>
                        </div>



                     </li>



                     <?php } ?>



                     <?php if(isset($diamond['diamondData']['clarity'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Clarity') ?></p>



                        </div>



                        <div class="diamonds-info">



                           <p><?php echo $diamond['diamondData']['clarity'] ?></p>



                        </div>



                     </li>



                     <?php } ?>



                     <?php if(isset($diamond['diamondData']['depth'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Depth %') ?></p>



                        </div>



                        <div class="diamonds-info">



                           <p><?php echo ($diamond['diamondData']['depth']) ? $diamond['diamondData']['depth'].'%' : '-'; ?></p>



                        </div>



                     </li>



                     <?php } ?>



                     <?php if(isset($diamond['diamondData']['table'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Table %') ?></p>



                        </div>



                        <div class="diamonds-info">



                           <p><?php echo ($diamond['diamondData']['table']) ? $diamond['diamondData']['table'].'%' : '-'; ?></p>



                        </div>



                     </li>



                     <?php } ?>



                     <?php if(isset($diamond['diamondData']['polish'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Polish') ?></p>



                        </div>



                        <div class="diamonds-info">



                           <p><?php echo ($diamond['diamondData']['polish']) ? $diamond['diamondData']['polish'] : '-'; ?></p>



                        </div>



                     </li>



                     <?php } ?>



                     <?php if(isset($diamond['diamondData']['symmetry'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Symmetry') ?></p>



                        </div>



                        <div class="diamonds-info">



                           <p><?php echo ($diamond['diamondData']['symmetry']) ? $diamond['diamondData']['symmetry'] : '-'; ?></p>



                        </div>



                     </li>



                     <!-- <li>



                        <div class="diamonds-details-title">



                           <p><?php /*echo __('Origin') ?></p>



                        </div>



                        <div class="diamonds-info">



                           <p><?php echo ($diamond['diamondData']['origin']) ? $diamond['diamondData']['origin'] : '-';*/ ?></p>



                        </div>



                     </li> -->



                     <?php } ?>



                     <?php if(isset($diamond['diamondData']['gridle'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Girdle') ?></p>



                        </div>



                        <div class="diamonds-info">



                           <p><?php echo ($diamond['diamondData']['gridle']) ? $diamond['diamondData']['gridle'] : '-'; ?></p>



                        </div>



                     </li>



                     <?php } ?>



                     <?php if(isset($diamond['diamondData']['culet'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Culet') ?></p>



                        </div>



                        <div class="diamonds-info">



                           <p><?php echo ($diamond['diamondData']['culet']) ? $diamond['diamondData']['culet'] : '-'; ?></p>



                        </div>



                     </li>



                     <?php } ?>



                     <?php if(isset($diamond['diamondData']['fluorescence'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Fluorescence') ?></p>



                        </div>



                        <div class="diamonds-info">



                           <p><?php echo ($diamond['diamondData']['fluorescence']) ? $diamond['diamondData']['fluorescence'] : '-'; ?></p>



                        </div>



                     </li>



                     <?php } ?>



                     <?php if(isset($diamond['diamondData']['measurement'])) { ?>



                     <li>



                        <div class="diamonds-details-title">



                           <p><?php echo __('Measurement') ?></p>



                        </div>



                        <div class="diamonds-info">



                           <p><?php echo ($diamond['diamondData']['measurement']) ? $diamond['diamondData']['measurement'] : '-'; ?></p>



                        </div>



                     </li>



                     <?php } ?>



                  </ul>

                  <?php if(sizeof((array)$diamond['diamondData']['diamondDeatilAdditionalInfo'])){ $additional_data = array(); ?>

                  <div class="specification-title"><h2><?php echo __('Additional information') ?></h2></div>

                  <ul>

                     <?php $additional_data = (array)$diamond['diamondData']['diamondDeatilAdditionalInfo'];                  

                     foreach ($additional_data as $field => $value) { if($field != '$id') { ?>

                        <li>

                           <div class="diamonds-details-title">

                              <p><?php echo $field ?></p>

                           </div>

                           <div class="diamonds-info">

                              <p><?php echo ($value) ? $value : '-'; ?></p>

                           </div>

                        </li>

                  <?php } } ?>

                  </ul>

                 <?php } ?>



               </div>



            </div>



         </div>



      </div>



   </div>



   <div class="search-form">



      <form id="search-diamonds-form" method="post" action="<?php echo $block->escapeUrl($block->getSearchFormAction()) ?>">

         <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">

         <input name="submitby" id="submitby" type="hidden" value="">



         <input name="viewmode" id="viewmode" type="hidden" value="list" />



         <input type="hidden" name="orderby" id="orderby" value="FltPrice" />



         <input type="hidden" name="direction" id="direction" value="ASC" />



         <input type="hidden" name="currentpage" id="currentpage" value="1" />



         <?php if($diamond['diamondData']['fancyColorMainBody']) { ?>



         <input type="hidden" name="filtermode" id="filtermode" value="navfancycolored">



         <?php } else if($diamond['diamondData']['certificate'] == 'GCAL'){ ?>



         <input type="hidden" name="filtermode" id="filtermode" value="navlabgrown">



         <?php } else { ?> 



         <input type="hidden" name="filtermode" id="filtermode" value="navstandard">



         <?php } ?>



         <?php  

         if($block->getRingCaratCookieData()){



            $setting = $block->getRingCaratCookieData();



            if($setting->caratmin > '0.00'){



/*               $TempCaratMin = ($setting->caratmin * 10) / 100;*/



               $CaratMin = ($setting->caratmin);



            }



            if($setting->caratmax > '0.00'){



               $CaratMax = ($setting->caratmax);



            }



         } else {



            if($diamond['diamondData']['caratWeight'] > '0.00'){



            $CaratMin = ($diamond['diamondData']['caratWeight']);



            $CaratMax = ($diamond['diamondData']['caratWeight']);



            } else {

               $CaratMin = $diamond['diamondData']['caratWeight'];



               $CaratMax = $diamond['diamondData']['caratWeight'];



            }

         }

         



         ?>

         

         <input type="hidden" name="diamond_shape[]" id="diamond_shape" value="<?php echo $diamond['diamondData']['shape'] ?>" />



         <input type="hidden" name="diamond_certificates[]" id="diamond_certificates" value="<?php echo $diamond['diamondData']['certificate'] ?>" />



         <input type="hidden" name="diamond_carats[from]" value="<?php echo $CaratMin; ?>" />



         <input type="hidden" name="diamond_carats[to]" value="<?php echo $CaratMax; ?>" />



         <input type="hidden" name="price[from]" value="0" />



         <input type="hidden" name="price[to]" value="100000" />



         <input type="hidden" name="diamond_table[from]" value="0" />



         <input type="hidden" name="diamond_table[to]" value="100" />



         <input type="hidden" name="diamond_depth[from]" value="0" />



         <input type="hidden" name="diamond_depth[to]" value="100" />



         <input name="itemperpage" id="itemperpage" type="hidden" value="<?=$block->getResultsPerPage(); ?>" />



         <input type="hidden" name="gemfind_diamond_origin" value="" />



         <input type="submit" name="Submit" id="submit" style="visibility: hidden;">



      </form>



   </div>



   <div class="result filter-advanced">



      <div style="text-align: center; margin: 50px; font-size: 16px;"><b><?php echo __('Loading Similar Diamonds...'); ?></b></div>



   </div>



</section>



<script>  



   require([



    'jquery'], function($) {



     $(window).bind("load", function() {

       $(".prinddia").attr('href','<?php echo $block->getUrl('diamondtools/product/printdiamond').'id/'.$diamond['diamondData']['diamondId']; ?>');

       $(".prinddia").printPage();



     });



   });



   function showLoader(){



      document.getElementById("gemfind-loading-mask").style.display ="block";



   }



</script>



<script>



   require([



       "jquery"



   ], function ($) {



            var src = $( 'div.diamention img' ).attr("data-src");  
            var mainimgsrc = $('div#diamondimg img').attr("data-src"); 


            imageExists1(src, function(exists) {



               if(exists){



                  $( 'div.diamention img' ).attr('src',src);



               } else {



                  $( 'div.diamention img' ).attr('src','<?php echo $this->getViewFileUrl('Gemfind_Ringbuilder::images/no-image.jpg') ?>');



               } 



            });

            imageExists1(mainimgsrc, function(exists) {
               if(exists){
                  $( 'div#diamondimg img' ).attr('src',mainimgsrc);
                  $( 'div#thumbdiamondimg img' ).attr('src',mainimgsrc);
               } else {
                  $( 'div#diamondimg img' ).attr('src','<?php echo $this->getViewFileUrl('Gemfind_Diamondsearch::images/no-image.jpg') ?>');
                  $( 'div#thumbdiamondimg img' ).attr('src','<?php echo $this->getViewFileUrl('Gemfind_Diamondsearch::images/no-image.jpg') ?>');
               } 
            });



      function imageExists1(url, callback) {



          var img = new Image();



          img.onload = function() { callback(true); };



          img.onerror = function() { callback(false); };



          img.src = url;



      }



   }); 



   require(['jquery','Magento_Ui/js/modal/modal'], function($,modal) {



      var options1 = {



                 type: 'popup',



                 responsive: true,



                 innerScroll: true,



                 modalClass: 'internalusemodel'



            };



            var options2 = {



                 type: 'popup',



                 responsive: true,



                 innerScroll: true,



                 title: 'Vendor Infromation',



                 modalClass: 'dealerinfopopup'



            };



            var popup = modal(options1, $('#auth-section'));



            var popup = modal(options2, $('#dealer-info-section'));



            $("#internaluselink").on('click',function(){



                $('#msg').html('');



                $('#internaluseform input').val('');



                $("#auth-section").modal("openModal");



            });



   });



   function internaluselink(){



         require([



         "jquery",'Magento_Ui/js/modal/modal'



         ], function ($) {



            $.ajax({



                url: '<?php echo $block->getBaseurl() ?>'+"ringbuilder/diamond/authenticate",



                data: $('#internaluseform').serialize(),



                type: 'POST',



                dataType: 'json',



                cache: true,



                beforeSend: function(settings) {



                    $('.loading-mask.gemfind-loading-mask').css('display', 'block');



                },



                success: function(response) {



                  if(response.output.status == 1){



                     $('#msg').html('<span class="success">'+response.output.msg+'</span>');



                     $("#auth-section").modal("closeModal");



                     $("#dealer-info-section").modal("openModal");



                  } else {



                     $('#msg').html('<span class="error">'+response.output.msg+'</span>');



                  }



                  $('.loading-mask.gemfind-loading-mask').css('display', 'none');



                }



            });



         });



      }



</script>

<style>
.list-inline.social-share::before {
    content: "";
    display: block;
    clear: both;
    padding: 0;
}
ul.list-inline.social-share {
    padding: 11px 0 0;
    overflow: hidden;
    float: none;
    width: 100%;
}
ul.list-inline.social-share li {
    list-style: none;
    display: inline-block;
    vertical-align: middle;
    margin: 0;
    padding-right: 5px;
}
ul.list-inline.social-share li span {
    position: relative;
    opacity: 1;
    padding: 0;
}
ul.list-inline.social-share li a {
    height: 19px;
    font-size: 11px !important;
    line-height: 20px !important;
    background-size: 13px 18px !important;
}
.list-inline.social-share li{height: 20px;}
.list-inline.social-share li.like_fb iframe {
    left: -9px;
}
</style>

<?php } else { ?>



<div class="diamond-nf">



   <?php echo __('Diamond not found. Please try again after some time.'); ?>  



</div>



<?php } ?>

<div id="popup-modal">

    <div class="note" style="display: none;"></div>

</div>
<input type="hidden" name="gemfind_rb_version" value="2.6" />