<?php
/**
 * @author Magneto Team
 * @copyright Copyright (c) 2021 Magneto (https://www.magnetoitsolutions.com)
 * @package Customer_Sell
 */

namespace Customer\Sell\Plugin;

use Magento\Framework\Mail\Template\TransportBuilder;

class Password
{
    /**
     * @var Helper
     */
    private $helper;

    public function __construct(
        \Customer\Sell\Helper\Data $helper
    ) {
        $this->helper = $helper;
    }

    public function aroundSetTemplateVars(TransportBuilder $subject, $proceed, $templateVars)
    {
        if (!empty($this->helper->getCustomerPassword())) {
            $templateVars['autogenerated_password'] = $this->helper->getCustomerPassword();
        }

        return $proceed($templateVars);
    }
}
