<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;

$controllerName = $this->getRequest()->getControllerName();
$actionName = $this->getRequest()->getActionName();
$routeName = $this->getRequest()->getRouteName();
$customblock = $block->getLayout()->createBlock('Magneto\Custom\Block\Addtocart');
$product = $finalPriceModel->getProduct();
$regularPrice = $product->getPrice();
$specialPrice = $product->getFinalPrice();
$pid = $product->getId();
$discount = $customblock->getDiscount($pid);

if ($actionName == 'view' && $controllerName == 'product' && $routeName == 'catalog' ) { ?>

<div class="childProductIdDiv no-display" id="childProductId" style=""></div>
<!-- <input type="hidden" name="childProductId" id="childProductId" /> -->
<span class="normal-price no-display" id="orgPrice">
        <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label' => __('As low as'),
            'price_id' => $block->getPriceId('product-price-' . $idSuffix),
            'price_type' => 'regularPrice',
            'include_container' => true,
            'schema' => $schema,
        ]);
        ?>
</span>
<div class="custom-price">     
    <div class="original">
        <div class="original discountPrice" id="replacePrice">
            <p class="price-title">
                <?php if ($discount) { ?>
                    <span class="org"><?php echo __('Original '); ?></span>
                <?php } ?>
                <?php echo __('Price'); ?>:</p>
            <p class="price" ><span class="price"><?php echo $block->renderAmount($priceModel->getAmount()); ?></span></p>
            <?php if ($discount) { ?>
            <p class="discount-per"><?php echo __('(').__('Discount ')._('<span class="per">'.$discount.'</span>%)'); ?></p>
        <?php } ?>
        </div>
    </div>

    <?php if ($block->hasSpecialPrice()) :?>
        <div class="special" id="specialPrice">
                <p><?php echo __('Special Price'); ?>:</p>
                <p class="price"><span class="price"><?php echo $block->renderAmount($finalPriceModel->getAmount()); ?></span></p>
        </div>
    <?php endif; ?>
</div>
<?php } else {
?>
<?php if ($block->hasSpecialPrice()) :?>
    <span class="special-price">
        <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Special Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
    <span class="old-price">
        <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
<?php else :?>
    <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
<?php endif; ?>

<?php if ($block->showMinimalPrice()) :?>
    <?php if ($block->getUseLinkForAsLowAs()) :?>
        <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else :?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; } ?>
