<div class="sell-item-btm">
	<div class="main-cnt">
	<div class="container">
	<div class="form-main">
		<div class="leftsec">
			<div class="maincont">
			<div class="tabsec">
				<div class="left-tag active"><a><?php echo __('in-person'); ?></a></div>
				<div class="left-tag"><a><?php echo __('online'); ?></a></div>
			</div>
			<div class="contentsec desktop">
				<h2><?php echo __('In-Person'); ?></h2>
				<div class="queans">
				<h4><?php echo __('Step 1: Upload certificate'); ?></h4>
				<h5><?php echo __('Upload certificate images for your diamonds to get an estimated quote from online.(GIA / IGI certified diamonds only)'); ?></h5>
				</div>
				<div class="queans">
				<h4><?php echo __('Step 2: Schedule A Meeting'); ?></h4>
				<h5><?php echo __('Schedule a time to come into Diamond ICQ to sell your jewellery.'); ?></h5>
				</div>
				<div class="queans">
				<h4><?php echo __('Step 3: Meet our diamond specialist'); ?></h4>
				<h5><?php echo __('Come to Diamond ICQ and meet our diamond specialist who would go over the value of your diamond with you.'); ?></h5>
				</div>
				<div class="queans">
				<h4><?php echo __('Step 4: Receive and accept an offer'); ?></h4>
				<h5><?php echo __('Diamond ICQ will offer you a competitive offer for your diamonds.'); ?></h5>
				</div>
				<div class="queans">
				<h4><?php echo __('Step 5: Receive Payment'); ?></h4>
				<h5><?php echo __('Once you accept our offer we will provide you with payment for your diamond.'); ?></h5>
				</div>
			</div>
			<div class="contentsec mobile">
                <h4><?php echo __('Upload certificate'); ?></h4>
                <h5><?php echo __('Upload certificate images for your diamonds to get an estimated quote from online.(GIA / IGI certified diamonds only)'); ?></h5>
            </div>
			</div>
		</div>
		<div class="rightsec">
			<div class="maincont">
			<h1><?php echo __('Get Your Quote Now'); ?></h1>
			<p><?php echo __('GIA/IGI Certified Diamond'); ?></p>
			<div class="formsec">
				<div class="title"><?php echo __('Select an option to upload'); ?></div>
				<div class="selectsec-title">
				<input type="radio" id="r1"  name="<?php echo __('Certificate and Jewellery Images'); ?>">
				<label class="label" ><span><?php echo __('Certificate and Jewellery Images'); ?></span></label>
				</div>
				<div class="selectsec-title">
				<input type="radio" id="r2" name="<?php echo __('Only Jewellery Image'); ?>">
				<label class="label" ><span><?php echo __('Only Jewellery Image'); ?></span></label>
				</div>
				<div class="selectsec-title">
				<input type="radio"  id="r3" name="<?php echo __('No Images.'); ?>">
				<label class="label" ><span><?php echo __('No Images.'); ?></span></label>
				</div>
				<div class="imgupload">
					<div class="btn">
						<span class="leftimg"></span>
						<span class="rightimg">
							<span><?php echo __('Upload Certificate and Jewellery Images');?></span>
							<span class="s2"><?php echo __('(Maximum - 10 Images)'); ?></span>
						</span>
					</div>
  					<input type="file" name="myfile" />
				</div>
				<div class="imgupload jewellery">
					<div class="mainsec">
					<div class="btn">
						<span class="leftimg"></span>
						<span class="rightimg">
							<span><?php echo __('Jewellery Images');?></span>
							<span class="s2"><?php echo __('(Maximum - 10 Images)'); ?></span>
						</span>
					</div>
  					<input type="file" name="myfile" />
  					</div>
				</div>
				<div class="imgupload multiple">
					<div class="btn">
						<div class="btn1">
						<div class="imgone">
							<div class="oneimg">
							<img class="uploadimg" src="<?php echo $this->getViewFileUrl('images/Rectangle.jpg'); ?>" >
							<img class="close" src="<?php echo $this->getViewFileUrl('images/close.svg'); ?>" >
							</div>
							<div class="oneimg">
							<img class="uploadimg" src="<?php echo $this->getViewFileUrl('images/Rectangle.jpg'); ?>" >
							<img class="close" src="<?php echo $this->getViewFileUrl('images/close.svg'); ?>" >
							</div>
							<div class="oneimg">
							<img class="uploadimg" src="<?php echo $this->getViewFileUrl('images/Rectangle.jpg'); ?>" >
							<img class="close" src="<?php echo $this->getViewFileUrl('images/close.svg'); ?>" >
							</div>
							<div class="oneimg">
							<img class="uploadimg" src="<?php echo $this->getViewFileUrl('images/Rectangle.jpg'); ?>" >
							<img class="close" src="<?php echo $this->getViewFileUrl('images/close.svg'); ?>" >
							</div>
							<div class="oneimg">
							<img class="uploadimg" src="<?php echo $this->getViewFileUrl('images/Rectangle.jpg'); ?>" >
							<img class="close" src="<?php echo $this->getViewFileUrl('images/close.svg'); ?>" >
							</div>
							<div class="oneimg">
							<img class="uploadimg" src="<?php echo $this->getViewFileUrl('images/Rectangle.jpg'); ?>" >
							<img class="close" src="<?php echo $this->getViewFileUrl('images/close.svg'); ?>" >
							</div>
							<div class="oneimg">
							<img class="uploadimg" src="<?php echo $this->getViewFileUrl('images/Rectangle.jpg'); ?>" >
							<img class="close" src="<?php echo $this->getViewFileUrl('images/close.svg'); ?>" >
							</div>
							<div class="oneimg">
							<img class="uploadimg" src="<?php echo $this->getViewFileUrl('images/Rectangle.jpg'); ?>" >
							<img class="close" src="<?php echo $this->getViewFileUrl('images/close.svg'); ?>" >
							</div>
							<div class="oneimg">
							<img class="uploadimg" src="<?php echo $this->getViewFileUrl('images/Rectangle.jpg'); ?>" >
							<img class="close" src="<?php echo $this->getViewFileUrl('images/close.svg'); ?>" >
							</div>
							<div class="oneimg">
							<img class="uploadimg new" src="<?php echo $this->getViewFileUrl('images/Rectangle717.jpg'); ?>" >
							</div>
						</div>
						</div>
					</div>	
				</div>
				<div class="field required">
					<input type="number" name="" placeholder="<?php echo __('Mobile No.'); ?>* ">
				</div>
				<div class="submit-btn"><button><?php echo __('upload'); ?></button></div>
			</div>

			<div class="meeting-sec main">
			    <h2><?php echo __('Schedule a Meeting.'); ?></h2>
			    <div class="date-apoinmentsec">
			    	<p><?php echo __('Schedule an appointment with our Diamond Expert.'); ?></p>
			    	<div class="date-apoinment-con">
			    	<div class="mainsec">
			    		<div class="btn">
						<span class="leftimg"><img src="<?php echo $this->getViewFileUrl('images/link.svg'); ?>" ></span>
						<span class="rightimg">
							<span><?php echo __('Make  An Appointment');?></span>
						</span>
						</div>
					</div>


			        <div class="submit-btn">
			        <div class="leftbtn"><button><?php echo __('previous'); ?></button></div>
			        <div class="rightbtn"><button><?php echo __('next'); ?></button></div>
			    	</div>
			    	</div>
			    </div>
			    
			</div>

			<div class="meeting-sec">
			    <h2><?php echo __('Schedule a Meeting. (1/2)'); ?></h2>
			    <div class="date-apoinmentsec">
			    	<div class="date-apoinment-con">
			    	<div class="field"><input type="" name="" placeholder="<?php echo __('Select Appointment Date'); ?> "></div>
			        <div class="submit-btn">
			        <div class="leftbtn"><button><?php echo __('previous'); ?></button></div>
			        <div class="rightbtn"><button><?php echo __('book now'); ?></button></div>
			    	</div>
			    	</div>
			    </div>
			    
			</div>


			<div class="fom-sec">
				 <h2><?php echo __('Please Fill The Form . (2/2)'); ?></h2>
				 <div class="form-detail">
				 	<div class="full-field">
				 	<div class="field left"><input type="" name="" placeholder="<?php echo __('First Name'); ?> "></div>
				 	<div class="field right"><input type="" name="" placeholder="<?php echo __('Last Name'); ?> "></div>
				 	</div>
				 	<div class="full-femail">
				 	<div class="field"><input type="" name="" placeholder="<?php echo __('Email'); ?> "></div>
				 	</div>	
				 	<div class="full-femail">
				 	<div class="field">
				 		<label><?php echo __('Preferred Method'); ?></label>
				 		<select>
				 			<option><?php echo __('Trade For Cash'); ?></option>
				 			<option><?php echo __('Trade For Cash 1'); ?></option>
				 			<option><?php echo __('Trade For Cash 2'); ?></option>
				 		</select>
				 	</div>
				 	</div>
				 	<div class="full-femail">
				 	<div class="field">
				 		<label><?php echo __('Item Description'); ?></label>
				 		<textarea></textarea>
				 	</div>
				 	</div>
				 	 <div class="submit-btn">
			        <div class="leftbtn"><button><?php echo __('previous'); ?></button></div>
			        <div class="rightbtn"><button><?php echo __('submit'); ?></button></div>
			    	</div>
				 </div>
			</div>


			<div class="thankyousec">
				<h1><?php echo __('Thank you'); ?></h1>
				<div class="content">
					<p><?php echo __('Thank you for submitting your product information. We are now processing your order.'); ?></p>
					<p><?php echo __('Item Name : abc'); ?></p>
					<p><?php echo __('Date: xx-xx-xxxx'); ?></p>
					<p><?php echo __('*Please contact service@diamondicq.com if there is any question.'); ?></p>
					<div class="submit-btn"><button><?php echo __('close'); ?></button></div>
				</div>
			</div>

			</div>
		</div>
	</div>
	</div>
	</div>
</div>