<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-11-29 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2019-12-04 11:07:49
 */
?>
<?php
/**
 * Categories block
 *
 * @var $block \Magepow\Categories\Block\Categories
 */

$categories  = $block->getCategories();
$heading     = $block->getHeading();
$description = $block->isShowDescription();
$itemAmount  = $block->getItemAmount();
if (empty($categories)) { return;
}
$selector     = 'alo-content-'.uniqid();
?>
<?php $visible = (int) $this->getData('visible'); ?>
<style type="text/css"><?php echo $this->getData('slide') ? '.' . $selector . ' .item{float:left; width:' . 100/$visible . '%} .'. $selector . ' .item:nth-child(n+' . ++$visible . '){display: none}' : ''  ?></style>
<?php if ($heading): ?>
    <div class="block-title">
        <h2 class="title m-0"><?php echo $heading ?></h2>
        <p class="sub-title"><?= __($this->getData('subtitle')); ?></p>
    </div>
<?php endif; ?>
<div class="magepow-categories <?php echo $selector ?>" data-mage-init='{"gridSlider": {}}'>
    <ul class="grid-slider"
        <?php foreach ($this->getFrontendCfg() as $opt):?>
            data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>'
        <?php endforeach;?> 
    >
        <?php foreach ($categories as $cat): ?>
            <?php $image = $this->getImageInfo($cat); ?>
            <li class="category-item item">
                <div class="category-item-info">
                    <div class="category-image-container">
                        <a class="category-url" href="<?php echo $this->getdata('link') ?>">
                            <img src="<?php echo $this->getImage($cat) ?>" alt="<?php echo $cat->getName() ?>"/>
                        </a>
                    </div>
                    <div class="category-item-details" style="visibility: hidden;    height: 1px;    margin-top: 0;">
                        <h3 class="category-item-name">
                            <a class="category-item-link" href="<?php echo $this->getdata('link') ?>">
                                <span class="category-name"><?php echo $cat->getName() ?></span>
                            </a>
                        </h3>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
