<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
    <div class="page-title-wrapper">
        <h1 class="page-title">   
            <span class="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Sign In') ?></span>
        </h1>
    </div>

    <div class="block-title">
        <span class="block-customer-login-heading" role="heading"
              aria-level="2"><?= __('Please log in to your account.') ?></span>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field email required placeholder1">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}" required>
                        <label class="floating-label1 label"><span><?= __('Email Address') ?></span></label>
                </div>
                <div class="field password required placeholder1">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}" required>
                        <label class="floating-label1 label"><span><?= __('Password*') ?></span></label>

                </div>
            <!--
             <div class="field forgot-password"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Password?') ?></span></a></div>
            -->
             
            <?php echo $block->getChildHtml('form_additional_info'); ?>
            <div class="actions-toolbar">
                <div class="primary"><button type="submit" class="fill-bg" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></button></div>
            </div>
            </fieldset>
        </form>
    </div>
</div>

