<?php
$currentStep = $block->getData('current_steps');
$viewModelHelper = $block->getData('view_model');

$helper = $this->helper("Magneto\FreeEngraving\Helper\Data");
$module_enable = $helper->isEnabled();

if ($module_enable && trim($currentStep)!='') {
   // print_r(get_class($block));exit;
$addtocart_engravingTextTypeLabel = '';
$addtocart_engravingTextType = '';
$addtocart_engravingTextLabel = '';
$addtocart_engravingText = '';

$setting = $block->getProduct();
$isAdded = 0;
if(trim($currentStep)!='' && trim($currentStep)=='ringsettings'){
    $currentRingSettingsId = $setting['ringData']['settingId'];
    $currentRingSettingsData = $viewModelHelper->getRingEngravingCookieData($currentRingSettingsId);
}else if(trim($currentStep)!='' && trim($currentStep)=='ringcompletes'){
    $currentRingSettings = $block->getSelectedRing();
    $currentRingSettingsId = $currentRingSettings['ringData']['settingId'];
    $currentRingSettingsData = $viewModelHelper->getRingEngravingCookieData($currentRingSettingsId);
} 
if(!empty($currentRingSettingsData)){
    if(isset($currentRingSettingsData['addtocart-engravingTextTypeLabel']) && trim($currentRingSettingsData['addtocart-engravingTextTypeLabel'])!=''){
        $isAdded = 1;
        $addtocart_engravingTextTypeLabel = trim($currentRingSettingsData['addtocart-engravingTextTypeLabel']);        
    }
    if(isset($currentRingSettingsData['addtocart-engravingTextType']) && trim($currentRingSettingsData['addtocart-engravingTextType'])!=''){
        $addtocart_engravingTextType = trim($currentRingSettingsData['addtocart-engravingTextType']);        
    }
    if(isset($currentRingSettingsData['addtocart-engravingTextLabel']) && trim($currentRingSettingsData['addtocart-engravingTextLabel'])!=''){
        $addtocart_engravingTextLabel = trim($currentRingSettingsData['addtocart-engravingTextLabel']);        
    }
    if(isset($currentRingSettingsData['addtocart-engravingText']) && trim($currentRingSettingsData['addtocart-engravingText'])!=''){
        $addtocart_engravingText = trim($currentRingSettingsData['addtocart-engravingText']);        
    }
}

//$_attributeValue = $_product->getResource()->getAttribute('free_engraving')->getFrontend()->getValue($_product);
$_attributeValue = 'Yes';    
$engavingImage = $this->getViewFileUrl('Magneto_FreeEngraving::images/ring/rose_gold_engraving.png');

$engravingFontOptions = $helper->getEngravingFontOptions();
$defaultFontCharacterLimit = '12';
foreach ($engravingFontOptions as $keys => $fontsOptions) {
    if(trim($addtocart_engravingTextType)!=''){
        if(trim($fontsOptions['label'])==trim($addtocart_engravingTextType)){
            $defaultFontCharacterLimit = $fontsOptions['data-character-limit'];    
        }
    }else{
        $defaultFontCharacterLimit = $fontsOptions['data-character-limit'];        
    }
}

if ($_attributeValue != 'No'): ?>
<input type="hidden" id="currentRingSettingId" value="<?=$currentRingSettingsId?>" />
<div id="custom_ringbuilder_engraving" class="ring-size prdctdrpdwn">
        <div class="product-info-engraving">
        	 <div class="img"> <img src="<?php echo $this->getViewFileUrl('images/engraving.svg'); ?>" alt="ring"></div>
            <a class="openBtn title" id="add_engraving" href="javascript:void(0)" <?php if($isAdded){ ?> style="display:none;" <?php } ?>><?php echo __('Add Engraving')?></a>
            <div class="edit_remove_engraving" 
            <?php if($isAdded){ ?> style="display:block;padding-top: 0;" <?php } else{ ?> style="display:none;" <?php }?> >
                <p id="preview_engraving_text" class="textEngravingValue for-preview" 
                <?php if($isAdded){ ?> style="display: inline-block;padding-top: 0;" <?php }else{ ?> style="display:none;" <?php }?> >
                    <?=$addtocart_engravingText;?>
                </p>
                <a href="javascript:void(0);" id="editEngraving" class="edit_engraving openBtn"><?php echo __('Edit Engraving')?></a> 
                <a href="javascript:void(0);" id="removeEngraving" class="remove_engraving"><?php echo __('Remove Engraving')?></a>
            </div>

            <div class="popup">
                <div class="popup-content">
                  <div id="engraving_popup_div">
                    <div class="form-group">
                        <span class="label"><?php echo __('Enter Engraving Text')?></span>
                        <textarea class="form-control" placeholder="<?php echo __('Enter Engraving Text')?>" rows="1" id="engravingText" data-max-length="<?=$defaultFontCharacterLimit?>" maxlength="<?=$defaultFontCharacterLimit?>"></textarea>
                        <p class="text-popup"><span class="engraving__available"><?=$defaultFontCharacterLimit?></span><?php echo __('Characters available.')?></p>
                    </div>
                    <div class="form-group">
                        <div>
                            <span class="label"><?php echo __('Choose Font')?></span>
                                <?php
                                $i = 0;
                                $selectedDefaultFont = '';
                                $selectCheckClass = '';
                                foreach ($engravingFontOptions as $keys => $fontsOptions) {

                                    $selectCheckClass = $selectedLabelClass = '';
                                    $fontOptionUrl = $this->getViewFileUrl("Magneto_FreeEngraving::images/fonts-image/".$fontsOptions['value'].".png");
                                    if ($i==0) {
                                        $selectedDefaultFont = 'js-'.$fontsOptions['value'];
                                        $selectCheckClass = 'checked="checked"';
                                        $selectedLabelClass = 'selected';
                            
                                    }
                                    ?>      
                                    <div class="group-lang">
                                        <input type="radio" class="radio" value="<?=$fontsOptions['value'];?>" name="engraving-text-type" data-font-text="<?=$fontsOptions['label'];?>" id="engraving_fonts_<?=$fontsOptions['value'];?>" data-character-limit = "<?=$fontsOptions['data-character-limit'];?>" data-isChineseFont = "<?=$fontsOptions['isChineseFont'];?>" <?=$selectCheckClass;?> />
                                    <label class="label_item <?=$selectedLabelClass;?>" for="engraving_fonts_<?=$fontsOptions['value'];?>"> <img src="<?=$fontOptionUrl;?>" alt="<?=$fontsOptions['label'];?>" title="<?=$fontsOptions['label'];?>"><span></span>
                                    </label>
                                </div>
                                
                                    <?php
                                    $i++;
                                }?>   
                        </div>
                    </div>
                    
                    <div class="engraving">
                        <span class="label"><?php echo __('Preview')?></span>
                        <p id="textEngravingValue" class="textEngravingValue <?=$selectedDefaultFont;?>"></p>
                        <div class="engraving__ring" style="background:url('<?php echo $engavingImage; ?>') no-repeat;background-size: cover;">
                        </div>
                        <span class="label desc">
                            <?php echo __('A 10x magnifying glass may be required to clearly read the engraving on your jewelry.')?>    
                    </span>
                    </div>

                    <div class="action-bar"><button type="submit" class="btn btn-default"><?php echo __('SAVE')?></button></div>
                    <p class="success-mag" style="display:none"><?php echo __('Engraving Added to product.')  ?></p>
                </div> 
                <a class="closeBtn" href="javascript:void(0)"> </a>
                </div>
            </div>
        </div>
    


</div>        
    <?php endif; ?>

<div id="add_to_cart_engraving_options">
    <input type="hidden" name="addtocart-engravingTextTypeLabel" id="addtocart-engravingTextTypeLabel" value="<?=$addtocart_engravingTextTypeLabel?>">
    <input type="hidden" name="addtocart-engravingTextTypeValue" id="addtocart-engravingTextTypeValue" value="">
    <input type="hidden" name="addtocart-engravingTextType" id="addtocart-engravingTextType" value="<?=$addtocart_engravingTextType?>">
    <input type="hidden" name="addtocart-engravingTextLabel" id="addtocart-engravingTextLabel" value="<?=$addtocart_engravingTextLabel?>">
    <input type="hidden" name="addtocart-engravingText" id="addtocart-engravingText" value="<?=$addtocart_engravingText?>">
</div>
<script>
    require([
        'jquery',
       // 'mage/mage',
       // 'Magento_Catalog/product/view/validation',
       // 'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';
        /*
        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });
               
                widget.catalogAddToCart('submitForm', $(form));
                
                return false;
            }
        });

        */
        <?php if(trim($currentStep)!='' && trim($currentStep)=='ringsettings'){ ?>
            $("#add_to_cart_engraving_options").appendTo("form#add_diamondtoring_form");
        <?php }else if(trim($currentStep)!='' && trim($currentStep)=='ringcompletes'){ ?>
            $("#add_to_cart_engraving_options").appendTo("form#product_addtocart_form");
        <?php }?>

        <?php if(trim($currentStep)!='' && trim($currentStep)=='ringsettings'){ ?>
            $("#custom_ringbuilder_engraving").appendTo("#ring-filter");
        <?php }else if(trim($currentStep)!='' && trim($currentStep)=='ringcompletes'){ ?>
            $("#custom_ringbuilder_engraving").insertAfter("#ring-content-data div.intro-field");
        <?php }?>
        
        function fontCharLimit(){
            var char_limit = $("input[type=radio][name='engraving-text-type']:checked").attr('data-character-limit');
            $("span#engraving__available").html(char_limit);
            $("#engravingText").attr("data-max-length",char_limit);
            $("#engravingText").attr("maxlength",char_limit);
        }

        // Open Popup
        $('.openBtn').on('click', function () {
            //alert("come here at openbtn click");
            fontCharLimit();
          $('.popup').fadeIn(300);
          //alert("after fadein");
        });
     
        // Close Popup
        $('.closeBtn').on('click', function () {
          $('.popup').fadeOut(300);
        });
     
        // Close Popup when Click outside
/*$('.popup').on('click', function () {



          //$('.popup').fadeOut(300);
        }).children().click(function () {
          return true;
        });
*/        
        $(document).mouseup(function(e){
            var container = $(".popup");

            // If the target of the click isn't the container
            if(!container.is(e.target) && container.has(e.target).length === 0){
                $('.popup').fadeOut(300);
            }
        });




 
    });

require(['jquery', 'Magneto_FreeEngraving/js/mymodal-component'],
    function ($) {
        
        return;
    }
);

</script>
<?php } ?>