<?php
/**
 * @author Gemfind Team
 */
?>
<?php

$settings = $block->getStyleSettingsRB();
$dealerid = $block->getDealerID();
if ($settings && sizeof($settings) > 0) {
    $selectedItemTextColor = '#ffffff';
    $buttonTextHoverColor = $buttonTextColor = '#ffffff';
    $sliderColor = $settings['settings']['hoverEffect'][0]->color2;
    $selectedItemColor = $settings['settings']['linkColor'][0]->color2;
    $selectedItemhoverColor = $settings['settings']['hoverEffect'][0]->color2;
    $gridColor = $settings['settings']['columnHeaderAccent'][0]->color2;
    $gridHoverColor = $settings['settings']['columnHeaderAccent'][0]->color2;
    $buttonBackgroundColor = $settings['settings']['callToActionButton'][0]->color2;
    $buttonhoverColor = $settings['settings']['callToActionButton'][0]->color2;
    $linkColor = $settings['settings']['linkColor'][0]->color2;
    $linkHoverColor = $settings['settings']['hoverEffect'][0]->color2;
    $additionalCSS = $block->getAdditionalCss();
    ?>
<script>
    var dealerid = '<?php echo $dealerid?>';
    require([
       "jquery"
   ], function ($) {
    $('body').addClass(dealerid);
    }); 
</script>
<style>
    .diamond-filter-title{background: <?=$gridColor ?>;}
    #search-rings .noUi-connect { background-color: <?=$linkColor ?>; border-color: <?=$linkColor ?>; }
    #search-rings .slider_wrapper .noUi-handle {background: <?=$linkColor ?>; border-color: <?=$linkColor ?>;}    
    .rings-search .ui-slider-horizontal .ui-slider-range { background-color: <?=$linkColor ?>; border-color: <?=$linkColor ?>; }
    .ui-slider .ui-slider-tooltip, .ringbuilder-settings-index .price-filter .ui-slider-handle { background-color: <?=$linkColor ?>; }
    .flow-tabs .tab-section li.tab-li.active a{background: <?=$gridColor ?>;}
    .flow-tabs .tab-section li.tab-li.active a:after{border-color: transparent transparent transparent <?=$gridColor ?>;}
    .diamond-filter-title ul li.active a, .diamond-filter-title ul li a:hover {color: <?=$linkHoverColor ?>; text-shadow: 0px 0px 1px <?=$linkHoverColor ?>;}
    .ringbuilder-settings-view .diamonds-info .product-controler ul li a { color: <?=$linkColor ?>;}
    .ringbuilder-settings-view .diamonds-info .product-controler ul li a:hover {color: <?=$linkHoverColor ?>;}
    .ringbuilder-settings-view .diamonds-info .diamond-action button{background-color: <?=$buttonBackgroundColor ?>; color: <?=$buttonTextColor ?>;}
    .filter-for-shape ul li .shape-type.selected {background: <?=$linkColor ?>;}
    .filter-for-shape ul li .shape-type:hover{background: <?=$linkHoverColor ?>;}
    .filter-for-shape .cut-main ul li.active {background: <?=$linkColor ?>; color: <?=$selectedItemTextColor ?>;}
    .filter-advanced .accordion:before, .change-view-result ul li.list-view a.active:before, .change-view-result ul li.grid-view a.active:before, .change-view-result ul li a.active:before, .search-in-table button{background-color: <?=$buttonBackgroundColor ?>; color: <?=$buttonTextColor ?>;}
    .flow-tabs .rings-search .color-filter ul li:hover { border-bottom: 2px solid <?=$selectedItemColor ?>;}
    .flow-tabs .rings-search .color-filter ul li.active.selected { border-bottom: 2px solid <?=$selectedItemColor ?>;}
    .ringbuilder-settings-index .searching-result .change-view ul li a.active{background-color: <?=$buttonBackgroundColor ?>; }
    .diamond-filter-title ul li a{color: #ffffff; }
    .grid-paginatin ul li.active {background: <?=$linkColor ?>; color: <?=$buttonTextColor ?>;}
    .grid-paginatin ul li.active a{background: <?=$linkColor ?>; color: <?=$buttonTextColor ?>;}
    .grid-paginatin ul li.active:hover, .diamond-page .diamond-action button.addtocart:hover, .prefrence-action .preference-btn:hover, .compare-actions .view-product:hover, .grid-paginatin a#compare-main:hover, .grid-paginatin ul li:not(.grid-previous):not(.grid-next) a:hover, .compare-actions .delete-row:before, .compare-actions .delete-row{background: <?=$linkHoverColor ?>; color: <?=$buttonTextHoverColor ?>; }
    .change-view-result ul li.list-view a:hover, .change-view-result ul li.grid-view a:hover, .change-view-result ul li a:hover{color: <?=$buttonTextHoverColor ?>; }
    .search-in-table button:hover { background-color: <?=$buttonhoverColor ?>; color: <?=$buttonTextHoverColor ?>; }
    .search-product-grid .product-details .product-box-pricing span {color: <?=$selectedItemColor ?>; }
    .product-details .product-box-action label {color: <?=$selectedItemColor ?>; }
    .product-details .product-box-action .state label:before { border: 2px solid <?=$selectedItemColor ?>; }
    .product-details .product-box-action .state label:after {border: 1px solid <?=$selectedItemColor ?>;}
    .product-details .product-box-action input[type="checkbox"]:checked~.state label:before {background: <?=$selectedItemColor ?>;}
    .product-details .product-box-action input[type="checkbox"]:checked~.state label:after {background-color: <?=$selectedItemColor ?>;}
    .product-controler ul li:before {background-color: <?=$selectedItemColor ?>;}
    .specification-title h4 a {color: <?=$linkColor ?>;}
    .diamond-request-form .form-field .diamond-action span {color: <?=$selectedItemColor ?>;}
    .diamond-page .diamond-action button.addtocart {background: <?=$buttonBackgroundColor ?>; color: <?=$buttonTextColor ?>; }
    .diamond-info h2 span {color: <?=$linkColor ?>; }
    .diamond-request-form .form-field label input:focus, .diamond-request-form .form-field label textarea:focus {border-color: <?=$selectedItemColor ?>;}
    .prefrence-action .preference-btn {background: <?=$buttonBackgroundColor ?>; color: <?=$buttonTextColor ?>; }
    .diamond-request-form .form-field .prefrence-area input:checked~label:before {background: <?=$selectedItemColor ?>;}
    .compare-product .filter-title ul.filter-left li.active a {color: <?=$linkHoverColor ?>; }
    .color-filter ul li.active, .filter-details .polish-depth ul li.active { border-bottom: 2px solid <?=$selectedItemColor ?>; color: <?=$buttonBackgroundColor ?>;}
    .color-filter ul li:hover, .filter-details .polish-depth ul li:hover, .filter-for-shape .cut-main ul li:hover {border-bottom: : 2px solid <?=$selectedItemColor ?>; color: <?=$buttonBackgroundColor ?>;}
    .ui-datepicker .ui-datepicker-prev span, .ui-datepicker .ui-datepicker-next span {border-color: transparent <?=$selectedItemColor ?> transparent transparent; }  
    .ui-datepicker .ui-datepicker-next span {border-color: transparent transparent transparent <?=$selectedItemColor ?>; }    
    .ui-datepicker .ui-datepicker-calendar .ui-datepicker-today {background: <?=$selectedItemColor ?>; }
    .grid-paginatin a#compare-main {background: <?=$buttonBackgroundColor ?>; color: <?=$buttonTextColor ?>;}
    .product-controler ul li a:hover {color: <?=$linkHoverColor ?>;}
    .product-slide-button .trigger-info:before{color:<?=$buttonBackgroundColor ?> !important; }
    .compare-actions .view-product {background: <?=$buttonBackgroundColor ?>; color: <?=$buttonTextColor ?>;}
    .compare-info table tbody tr th:nth-child(1) a:hover:before, .compare-info table tbody tr th:nth-child(1) a:before{background: <?=$buttonBackgroundColor ?>;}
    .compare-product .filter-title ul.filter-left li a{color:<?=$linkColor ?>;}
    .compare-product .filter-title ul.filter-left li a:hover{color:<?=$linkHoverColor ?>;}
    .sumo_pagesize .optWrapper ul.options li.opt.selected{background-color: #E4E4E4; color: #000;}
    .SumoSelect > .optWrapper.multiple > .options li.opt.selected span i, .SumoSelect .select-all.selected > span i{background-color: <?=$buttonBackgroundColor.' !important' ?>;}
    .diamond-report .view_text a{color:<?=$buttonBackgroundColor ?> !important;}
    .internalusemodel.modal-slide .modal-inner-wrap, .dealerinfopopup.modal-slide .modal-inner-wrap{border:2px solid <?=$selectedItemColor ?>;}
    .internalusemodel.modal-slide header button, .dealerinfopopup.modal-slide header button, #internaluseform button.preference-btn{background:<?=$buttonBackgroundColor.' !important' ?>;  box-shadow: none; color: <?=$buttonTextColor ?>; }
    a.internaluselink {color: <?=$buttonBackgroundColor ?>;}
    a.internaluselink:hover {color: <?=$linkHoverColor ?>;}
    .internalusemodel .msg{padding: 2px; margin-bottom: 2px;}
    .internalusemodel .msg .error{color: #e40f0f;}
    .internalusemodel .msg .success{color: #29a529;}
    .breadcrumbs ul li a{color: <?=$linkColor ?> !important;}
    .breadcrumbs ul li a:hover{color: <?=$linkHoverColor ?> !important;}
    svg#Capa_1{fill: <?=$linkColor ?>;}
    svg#Capa_1:hover{fill: <?=$linkHoverColor ?>;}
    .ringbuilder-settings-view .specification-title a svg{fill:<?=$buttonBackgroundColor ?>;}
    .specification-title a svg{fill:<?=$buttonBackgroundColor ?>!important;}
     .flow-tabs .rings-search .shapepricefiltersection .filter-alignment-right .shape-type:hover{    background: <?=$linkHoverColor ?>;}
     .ringbuilder-settings-view .diamonds-info .diamond-action a.tryonbtn {background: <?=$buttonBackgroundColor ?> !important; color: <?=$buttonTextColor ?> !important; }
    <?=$additionalCSS ?>
</style>
<?php } ?>
