<div class="top-block">
    <div class="block-title"><h3><?= __("Your Quote")?></h3></div>
    <div class="list-grid-view" >
        <div class="modes">
            <div class="gridview"><a class="changeview" id="quote_grid_view" href="javascript:void(0);" data-view='gridview'><span><?= __("GridView")?></span></a></div>
            <div class="listview"><a class="changeview active" id="quote_list_view" href="javascript:void(0);" data-view='listview'><span><?= __("ListView")?></span></a></div>
        </div>
    </div>
    <div class="sorting-filters">
        <select class="changesort" id="quote-sorting-filter">
            <?php foreach ($block->getSortByOptions() as $option => $label): ?>
                <option value="<?= $option ?>"><?= __($label) ?></option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Customer_Sell/js/quote/filter": <?php echo $block->getJsConfig(); ?>
        }
    }
</script>