<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Block\Widget\Name;

/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$helper = $this->helper("Magneto\CustomerAccountCustomization\Helper\Data");
?>
<form class="form form-edit-account"
      action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Account Information')) ?></span></legend><br>
        <?= $block->getLayout()->createBlock(Name::class)->setObject($block->getCustomer())->toHtml() ?>

        <div class="field email required" data-container="change-email">
            <div class="control placeholder1">
                <input type="email" name="email" id="email" autocomplete="email" data-input="change-email"
                       value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       class="input-text"
                       data-validate="{required:true, 'validate-email':true}" required/>
               <label class="label floating-label1" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            </div>
        </div>
        <div class="field telephone required" >
            <div class="control placeholder1">
                <input type="tel" name="phone_number" id="phone_number"
                       value="<?= $block->escapeHtmlAttr($helper->getCustomerPhone()) ? $block->escapeHtmlAttr($helper->getCustomerPhone()) : '+852' ?>"
                       title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                       class="input-text required-entry"
                       required/>
               <label class="label floating-label1 floating is" for="phone_number"><?= $block->escapeHtml(__('Phone Number')) ?></label>
            </div>
        </div>
        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>
        <div class="field choice" style="display:none;">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1"
                   title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"
                 class="checkbox" />
            <label class="label" for="change-password">
                <span><?= $block->escapeHtml(__('Change Password')) ?></span>
            </label>
        </div>
        
        <a href="javascript:void(0);" id="changepass"><?= $block->escapeHtml(__('Change Password')) ?></a>
    </fieldset>
    <fieldset class="fieldset password" data-container="change-email-password">
        <legend class="legend">
            <span data-title="change-email-password"><?= $block->escapeHtml(__('Change Email and Password')) ?></span>
        </legend><br>


    </fieldset>
  <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" id="btn_submit" class="action save primary" 
            title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $block->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>

  <div class="callfor-popup" style="display:none;">
        <div class="modal-content">
            <form class="form form-edit-account"
                action="<?= $block->escapeUrl($block->getUrl('customeraccounts/resetpassword/index')) ?>"
                method="post" id="form-validate1"
                enctype="multipart/form-data"
                data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
                autocomplete="off">  
                <input type="hidden" id="change_my_password" name="change_my_password" value="1"> 
                <div class="field password current required">
                    <div class="control placeholder1">
                        <input type="password" class="input-text" name="current_password" id="current-password"
                               data-input="current-password"
                               autocomplete="off" required/>
                           <label class="label floating-label1" for="current-password">
                            <span><?= $block->escapeHtml(__('Current Password')) ?></span>
                            </label>
                    </div>
                </div>
                <div class="field new password required" data-container="new-password">
                    <div class="control placeholder1">
                        <?php $minCharacterSets = $block->getRequiredCharacterClassesNumber() ?>
                        <input type="password" class="input-text" name="password" id="password"
                            data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                            data-password-min-character-sets="<?= $block->escapeHtml($minCharacterSets) ?>"
                            data-input="new-password"
                            data-validate="{required:true, 'validate-customer-password':true}"
                            autocomplete="off" required/>
                            <label class="label floating-label1" for="password">
                                <span><?= $block->escapeHtml(__('New Password')) ?></span>
                            </label>
                        <div id="password-strength-meter-container" data-role="password-strength-meter" 
                        aria-live="polite">
                            <div id="password-strength-meter" class="password-strength-meter">
                                <?= $block->escapeHtml(__('Password Strength')) ?>:
                                <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                    <?= $block->escapeHtml(__('No Password')) ?>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="field confirmation password required" data-container="confirm-password">
                    <div class="control placeholder1">
                        <input type="password" class="input-text" name="password_confirmation" 
                            id="password-confirmation" data-input="confirm-password"
                                autocomplete="off" required/>
                        <label class="label floating-label1" for="password-confirmation">
                            <span><?= $block->escapeHtml(__('Confirm New Password')) ?></span>
                        </label>
                    </div>
                </div>
                <div class="field choice" data-bind="scope: 'showPassword'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
                <button type="submit" class="action save primary" id="store_reset_btn" 
                title="<?= $block->escapeHtmlAttr(__("Reset Password")); ?>">
                    <span><?= $block->escapeHtmlAttr(__("Reset Password")); ?></span>
                </button>
            </form>
        </div>
    </div>    

<?php $ignore = /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null';
$scriptString = <<<script
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = {$ignore};

        dataForm.mage('validation', {
script;
if ($_dob->isEnabled()):
    $scriptString .= <<<script
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
script;
else:
    $scriptString .= <<<script
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
script;
endif;
$scriptString .= <<<script
        });

    });
script;
$scriptString1 = <<<script
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate1');
        var ignore = {$ignore};
        dataForm.mage('validation', {});
    });
script;

?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString1, false) ?>
<?php $changeEmailAndPasswordTitle = $block->escapeHtml(__('Change Email and Password')) ?>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs($changeEmailAndPasswordTitle) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        },
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "showPassword": {
                        "component": "Magento_Customer/js/show-password",
                        "passwordSelector": "#current-password,#password,#password-confirmation"
                    }
                }
            }
        }
    }
</script>
<script>
    
   require(
       [
           'jquery',
           'Magento_Ui/js/modal/modal'
       ],
       function (
           $,
           modal
       ) {
           var modaloption = {
               type: 'popup',
               modalClass: 'change-password-popup',
               responsive: true,
               innerScroll: true,
               clickableOverlay: true,
               title: '<?= $block->escapeHtmlAttr(__("Reset Password")); ?>',
               buttons: []
           };
           var callforoption = modal(modaloption, $('.callfor-popup'));
           //$('.callfor-popup').modal('openModal');
            $("#changepass").click(function(){
              //$("#change-password").prop("checked", true); 
                if($("#change-password").prop("checked") == false){
                    $("#change-password").click(); 
                }
                $('.callfor-popup').modal('openModal');
            });
            /*
            $("#store_reset_btn").click(function(){
              if($("#change-password").prop("checked") == false){
                    $("#change-password").click(); 
              }  
              $('.callfor-popup').modal('hide');
              $("#btn_submit").submit();
            });

            */
            <?php if ($block->getChangePassword()) { ?>
             $("#changepass").click();
            <?php }?>        
            
       }
   );
</script>