<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper"><?php echo __('Thank you for your purchase!'); ?></span>
    </h1>
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()):?>
            <div class="hor-line"><hr></div>
            <div class="orderidsec">
            <span><?php echo __('Order ID'); ?>:</span><strong><?php echo $block->getOrderId(); ?></strong>
            </div>
        <?php endif;?>
            <p><?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php echo $block->getUrl('ringbuilder/settings'); ?>"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>
    </div>
</div>
