<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product description template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */

if ( trim($block->getProduct()->getDescription()) != '') {
?>
<div class="title"><?php echo __('Product Description'); ?></div>
<?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute(
    $block->getProduct(),
    $block->getProduct()->getDescription(),
    'description'
); ?>
<?php } ?>
