<div class="product-summary">
	<div class="container">
		<div class="maincontent">
			<div class="title"><?php echo __('Product Summary'); ?></div>
			<div class="title sub"><?php echo __('Premium Diamond Engagement Ring'); ?></div>
			<div class="left">
				<div class="title"><?php echo __('Ring Information'); ?></div>
				<div class="tab">
					<div class="label"><?php echo __('Stock Number'); ?></div>
					<div class="value"><?php echo __('1236547892'); ?></div>
				</div>
				<div class="tab">
					<div class="label"><?php echo __('Height'); ?></div>
					<div class="value"><?php echo __('1.8 mm'); ?></div>
				</div>
				<div class="tab">
					<div class="label"><?php echo __('Width'); ?></div>
					<div class="value"><?php echo __('1.8 mm'); ?></div>
				</div>
			</div>
			<div class="right">
				<div class="title"><?php echo __('Diamond Information'); ?></div>
				<div class="tab">
					<div class="label"><?php echo __('Minimum Number of Round Diamonds'); ?></div>
					<div class="value"><?php echo __('3'); ?></div>
				</div>
				<div class="tab">
					<div class="label"><?php echo __('Minimum Carat Total Weight (ct. tw.) '); ?></div>
					<div class="value"><?php echo __('3 Ct'); ?></div>
				</div>
				<div class="tab">
					<div class="label"><?php echo __('Average Color'); ?></div>
					<div class="value"><?php echo __('xx'); ?></div>
				</div>
				<div class="tab">
					<div class="label"><?php echo __('Average Clarity'); ?></div>
					<div class="value"><?php echo __('xx'); ?></div>
				</div>
				<div class="tab">
					<div class="label"><?php echo __('Setting Type'); ?></div>
					<div class="value"><?php echo __('xx'); ?></div>
				</div>
			</div>
		</div>
	</div>
</div>