<div class="product-shipping">
	<div class="container">
		<div class="maincontent">
			<div class="title"><?php echo __('Shipping  Details'); ?></div>
			<div class="main">
				<div class="tab">
					<div class="label"><?php echo __('Order By'); ?></div>
					<div class="value"><?php echo __('6PM EDT Today'); ?></div>
				</div>
				<div class="tab">
					<div class="label"><?php echo __('Shipping Date'); ?></div>
					<div class="value"><?php echo __('XX-XX-XXXX'); ?></div>
				</div>
				<div class="tab">
					<div class="label"><?php echo __('Shipping Via'); ?></div>
					<div class="value"><?php echo __('FedEx'); ?></div>
				</div>
			</div>
		</div>
	</div>
</div>